package pe.com.mig.model.entity.sppi;
// Generated 11/06/2016 05:48:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TEspecifica generated by hbm2java
 */
@Entity
@Table(name = "t_especifica", schema = "sppi")
public class TEspecifica implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long srl_id_esp;
	private String chr_cod_especifica;
	private String var_nom_especifica;	
	private String chr_anio;
	private String chr_estado;
	private Integer int_idmigra;

	public TEspecifica() {
		super();
	}

	public TEspecifica(Long srl_id_esp) {
		this.srl_id_esp = srl_id_esp;
	}

	public TEspecifica(Long srl_id_esp, String chr_cod_especifica, String var_nom_especifica, String chr_anio,
			String chr_estado, Integer int_idmigra) {
		super();
		this.srl_id_esp = srl_id_esp;
		this.chr_cod_especifica = chr_cod_especifica;
		this.var_nom_especifica = var_nom_especifica;
		this.chr_anio = chr_anio;
		this.chr_estado = chr_estado;
		this.int_idmigra = int_idmigra;
	}

	@Id
	@Column(name = "srl_id_esp", unique = true, nullable = false)
	public Long getSrl_id_esp() {
		return this.srl_id_esp;
	}

	public void setSrl_id_esp(Long srl_id_esp) {
		this.srl_id_esp = srl_id_esp;
	}

	@Column(name = "chr_cod_especifica", length = 25)
	public String getChr_cod_especifica() {
		return this.chr_cod_especifica;
	}

	public void setChr_cod_especifica(String chr_cod_especifica) {
		this.chr_cod_especifica = chr_cod_especifica;
	}

	@Column(name = "var_nom_especifica", length = 250)
	public String getVar_nom_especifica() {
		return this.var_nom_especifica;
	}

	public void setVar_nom_especifica(String var_nom_especifica) {
		this.var_nom_especifica = var_nom_especifica;
	}

	@Column(name = "chr_anio", length = 4)
	public String getChr_anio() {
		return this.chr_anio;
	}

	public void setChr_anio(String chr_anio) {
		this.chr_anio = chr_anio;
	}

	@Column(name = "chr_estado", length = 1)
	public String getChr_estado() {
		return this.chr_estado;
	}

	public void setChr_estado(String chr_estado) {
		this.chr_estado = chr_estado;
	}

	@Column(name = "int_idmigra")
	public Integer getInt_idmigra() {
		return this.int_idmigra;
	}

	public void setInt_idmigra(Integer int_idmigra) {
		this.int_idmigra = int_idmigra;
	}
	
}
