package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administracionareanatural generated by hbm2java
 */
@Entity
@Table(name = "administracionareanatural", schema = "sernanp")
public class Administracionareanatural implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idadministracionareanatural;
	private String nombreadministracionareanatural;
	private String siglasadministracionareanatural;
	private Set<Areanatural> areanaturals = new HashSet<Areanatural>(0);

	public Administracionareanatural() {
	}

	public Administracionareanatural(int idadministracionareanatural) {
		this.idadministracionareanatural = idadministracionareanatural;
	}

	public Administracionareanatural(int idadministracionareanatural, String nombreadministracionareanatural,
			String siglasadministracionareanatural, Set<Areanatural> areanaturals) {
		this.idadministracionareanatural = idadministracionareanatural;
		this.nombreadministracionareanatural = nombreadministracionareanatural;
		this.siglasadministracionareanatural = siglasadministracionareanatural;
		this.areanaturals = areanaturals;
	}

	@Id
	@Column(name = "idadministracionareanatural", unique = true, nullable = false)
	public int getIdadministracionareanatural() {
		return this.idadministracionareanatural;
	}

	public void setIdadministracionareanatural(int idadministracionareanatural) {
		this.idadministracionareanatural = idadministracionareanatural;
	}

	@Column(name = "nombreadministracionareanatural", length = 250)
	public String getNombreadministracionareanatural() {
		return this.nombreadministracionareanatural;
	}

	public void setNombreadministracionareanatural(String nombreadministracionareanatural) {
		this.nombreadministracionareanatural = nombreadministracionareanatural;
	}

	@Column(name = "siglasadministracionareanatural", length = 20)
	public String getSiglasadministracionareanatural() {
		return this.siglasadministracionareanatural;
	}

	public void setSiglasadministracionareanatural(String siglasadministracionareanatural) {
		this.siglasadministracionareanatural = siglasadministracionareanatural;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administracionareanatural")
	public Set<Areanatural> getAreanaturals() {
		return this.areanaturals;
	}

	public void setAreanaturals(Set<Areanatural> areanaturals) {
		this.areanaturals = areanaturals;
	}

}
