package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Areanatural generated by hbm2java
 */
@Entity
@Table(name = "areanatural", schema = "sernanp")
public class Areanatural implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idareanatural;
	private Administracionareanatural administracionareanatural;
	private Categoriaanp categoriaanp;
	private Enlaceterritorial enlaceterritorial;
	private String codareanatural;
	private String desareanatural;
	private Integer estado;
	private String ubicacionareanatural;
	private Integer flagactivoareanatural;
	private String siglaareanatural;
	private Date fechacreacion;
	private String baselegalcreacion;
	private Integer gid;
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Areanatural() {
	}

	public Areanatural(int idareanatural, Administracionareanatural administracionareanatural,
			Enlaceterritorial enlaceterritorial) {
		this.idareanatural = idareanatural;
		this.administracionareanatural = administracionareanatural;
		this.enlaceterritorial = enlaceterritorial;
	}

	public Areanatural(int idareanatural, Administracionareanatural administracionareanatural,
			Categoriaanp categoriaanp, Enlaceterritorial enlaceterritorial, String codareanatural,
			String desareanatural, Integer estado, String ubicacionareanatural, Integer flagactivoareanatural,
			String siglaareanatural, Date fechacreacion, String baselegalcreacion, Integer gid, Set<Sede> sedes) {
		this.idareanatural = idareanatural;
		this.administracionareanatural = administracionareanatural;
		this.categoriaanp = categoriaanp;
		this.enlaceterritorial = enlaceterritorial;
		this.codareanatural = codareanatural;
		this.desareanatural = desareanatural;
		this.estado = estado;
		this.ubicacionareanatural = ubicacionareanatural;
		this.flagactivoareanatural = flagactivoareanatural;
		this.siglaareanatural = siglaareanatural;
		this.fechacreacion = fechacreacion;
		this.baselegalcreacion = baselegalcreacion;
		this.gid = gid;
		this.sedes = sedes;
	}

	@Id
	@Column(name = "idareanatural", unique = true, nullable = false)
	public int getIdareanatural() {
		return this.idareanatural;
	}

	public void setIdareanatural(int idareanatural) {
		this.idareanatural = idareanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idadministracionareanatural", nullable = false)
	public Administracionareanatural getAdministracionareanatural() {
		return this.administracionareanatural;
	}

	public void setAdministracionareanatural(Administracionareanatural administracionareanatural) {
		this.administracionareanatural = administracionareanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoriaanp")
	public Categoriaanp getCategoriaanp() {
		return this.categoriaanp;
	}

	public void setCategoriaanp(Categoriaanp categoriaanp) {
		this.categoriaanp = categoriaanp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idenlaceterritorial", nullable = false)
	public Enlaceterritorial getEnlaceterritorial() {
		return this.enlaceterritorial;
	}

	public void setEnlaceterritorial(Enlaceterritorial enlaceterritorial) {
		this.enlaceterritorial = enlaceterritorial;
	}

	@Column(name = "codareanatural", length = 4)
	public String getCodareanatural() {
		return this.codareanatural;
	}

	public void setCodareanatural(String codareanatural) {
		this.codareanatural = codareanatural;
	}

	@Column(name = "desareanatural", length = 200)
	public String getDesareanatural() {
		return this.desareanatural;
	}

	public void setDesareanatural(String desareanatural) {
		this.desareanatural = desareanatural;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "ubicacionareanatural", length = 250)
	public String getUbicacionareanatural() {
		return this.ubicacionareanatural;
	}

	public void setUbicacionareanatural(String ubicacionareanatural) {
		this.ubicacionareanatural = ubicacionareanatural;
	}

	@Column(name = "flagactivoareanatural")
	public Integer getFlagactivoareanatural() {
		return this.flagactivoareanatural;
	}

	public void setFlagactivoareanatural(Integer flagactivoareanatural) {
		this.flagactivoareanatural = flagactivoareanatural;
	}

	@Column(name = "siglaareanatural", length = 10)
	public String getSiglaareanatural() {
		return this.siglaareanatural;
	}

	public void setSiglaareanatural(String siglaareanatural) {
		this.siglaareanatural = siglaareanatural;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreacion", length = 13)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "baselegalcreacion", length = 30)
	public String getBaselegalcreacion() {
		return this.baselegalcreacion;
	}

	public void setBaselegalcreacion(String baselegalcreacion) {
		this.baselegalcreacion = baselegalcreacion;
	}

	@Column(name = "gid")
	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areanatural")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
