package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Areaorganica generated by hbm2java
 */
@Entity
@Table(name = "areaorganica", schema = "sernanp")
public class Areaorganica implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idarea;
	private Areaorganica areaorganica;
	private Sede sede;
	private Tablatipo tablatipo;
	private String codarea;
	private String desarea;
	private Integer telefonoareaorganica;
	private String direccionareaorganica;
	private Integer faxareaorganica;
	private Set<Areaorganica> areaorganicas = new HashSet<Areaorganica>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Areaorganica() {
	}

	public Areaorganica(int idarea, Sede sede) {
		this.idarea = idarea;
		this.sede = sede;
	}

	public Areaorganica(int idarea, Areaorganica areaorganica, Sede sede, Tablatipo tablatipo, String codarea,
			String desarea, Integer telefonoareaorganica, String direccionareaorganica, Integer faxareaorganica,
			Set<Areaorganica> areaorganicas, Set<Usuario> usuarios) {
		this.idarea = idarea;
		this.areaorganica = areaorganica;
		this.sede = sede;
		this.tablatipo = tablatipo;
		this.codarea = codarea;
		this.desarea = desarea;
		this.telefonoareaorganica = telefonoareaorganica;
		this.direccionareaorganica = direccionareaorganica;
		this.faxareaorganica = faxareaorganica;
		this.areaorganicas = areaorganicas;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "idarea", unique = true, nullable = false)
	public int getIdarea() {
		return this.idarea;
	}

	public void setIdarea(int idarea) {
		this.idarea = idarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idareapadre")
	public Areaorganica getAreaorganica() {
		return this.areaorganica;
	}

	public void setAreaorganica(Areaorganica areaorganica) {
		this.areaorganica = areaorganica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsede", nullable = false)
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoarea")
	public Tablatipo getTablatipo() {
		return this.tablatipo;
	}

	public void setTablatipo(Tablatipo tablatipo) {
		this.tablatipo = tablatipo;
	}

	@Column(name = "codarea", length = 4)
	public String getCodarea() {
		return this.codarea;
	}

	public void setCodarea(String codarea) {
		this.codarea = codarea;
	}

	@Column(name = "desarea", length = 60)
	public String getDesarea() {
		return this.desarea;
	}

	public void setDesarea(String desarea) {
		this.desarea = desarea;
	}

	@Column(name = "telefonoareaorganica")
	public Integer getTelefonoareaorganica() {
		return this.telefonoareaorganica;
	}

	public void setTelefonoareaorganica(Integer telefonoareaorganica) {
		this.telefonoareaorganica = telefonoareaorganica;
	}

	@Column(name = "direccionareaorganica", length = 250)
	public String getDireccionareaorganica() {
		return this.direccionareaorganica;
	}

	public void setDireccionareaorganica(String direccionareaorganica) {
		this.direccionareaorganica = direccionareaorganica;
	}

	@Column(name = "faxareaorganica")
	public Integer getFaxareaorganica() {
		return this.faxareaorganica;
	}

	public void setFaxareaorganica(Integer faxareaorganica) {
		this.faxareaorganica = faxareaorganica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaorganica")
	public Set<Areaorganica> getAreaorganicas() {
		return this.areaorganicas;
	}

	public void setAreaorganicas(Set<Areaorganica> areaorganicas) {
		this.areaorganicas = areaorganicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaorganica")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
