package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", schema = "sernanp")
public class Login implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idlogin;
	private Sistema sistema;
	private Usuario usuario;
	private String clave;
	private String usuario_1;
	private Date fecha;

	public Login() {
	}

	public Login(int idlogin, Sistema sistema, Usuario usuario) {
		this.idlogin = idlogin;
		this.sistema = sistema;
		this.usuario = usuario;
	}

	public Login(int idlogin, Sistema sistema, Usuario usuario, String clave, String usuario_1, Date fecha) {
		this.idlogin = idlogin;
		this.sistema = sistema;
		this.usuario = usuario;
		this.clave = clave;
		this.usuario_1 = usuario_1;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "idlogin", unique = true, nullable = false)
	public int getIdlogin() {
		return this.idlogin;
	}

	public void setIdlogin(int idlogin) {
		this.idlogin = idlogin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsistema", nullable = false)
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "usuario", length = 50)
	public String getUsuario_1() {
		return this.usuario_1;
	}

	public void setUsuario_1(String usuario_1) {
		this.usuario_1 = usuario_1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
