package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", schema = "sernanp")
public class Modulo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idmodulo;
	private String nombremodulo;
	private String nombrecortomodulo;
	private String imgmodulo;
	private Integer nivelmodulo;
	private Integer niveldependemodulo;
	private Integer ordenmodulo;
	private Integer flagmodulo;
	private String hrefmodulo;
	private String titlemodulo;

	public Modulo() {
	}

	public Modulo(int idmodulo) {
		this.idmodulo = idmodulo;
	}

	public Modulo(int idmodulo, String nombremodulo, String nombrecortomodulo, String imgmodulo, Integer nivelmodulo,
			Integer niveldependemodulo, Integer ordenmodulo, Integer flagmodulo, String hrefmodulo,
			String titlemodulo) {
		this.idmodulo = idmodulo;
		this.nombremodulo = nombremodulo;
		this.nombrecortomodulo = nombrecortomodulo;
		this.imgmodulo = imgmodulo;
		this.nivelmodulo = nivelmodulo;
		this.niveldependemodulo = niveldependemodulo;
		this.ordenmodulo = ordenmodulo;
		this.flagmodulo = flagmodulo;
		this.hrefmodulo = hrefmodulo;
		this.titlemodulo = titlemodulo;
	}

	@Id
	@SequenceGenerator(name = "seq_modulo", sequenceName = "sernanp.modulo_idmodulo_seq")
	@GeneratedValue(generator = "seq_modulo")
	@Column(name = "idmodulo", unique = true, nullable = false)
	public int getIdmodulo() {
		return this.idmodulo;
	}

	public void setIdmodulo(int idmodulo) {
		this.idmodulo = idmodulo;
	}

	@Column(name = "nombremodulo", length = 45)
	public String getNombremodulo() {
		return this.nombremodulo;
	}

	public void setNombremodulo(String nombremodulo) {
		this.nombremodulo = nombremodulo;
	}

	@Column(name = "nombrecortomodulo", length = 45)
	public String getNombrecortomodulo() {
		return this.nombrecortomodulo;
	}

	public void setNombrecortomodulo(String nombrecortomodulo) {
		this.nombrecortomodulo = nombrecortomodulo;
	}

	@Column(name = "imgmodulo", length = 250)
	public String getImgmodulo() {
		return this.imgmodulo;
	}

	public void setImgmodulo(String imgmodulo) {
		this.imgmodulo = imgmodulo;
	}

	@Column(name = "nivelmodulo")
	public Integer getNivelmodulo() {
		return this.nivelmodulo;
	}

	public void setNivelmodulo(Integer nivelmodulo) {
		this.nivelmodulo = nivelmodulo;
	}

	@Column(name = "niveldependemodulo")
	public Integer getNiveldependemodulo() {
		return this.niveldependemodulo;
	}

	public void setNiveldependemodulo(Integer niveldependemodulo) {
		this.niveldependemodulo = niveldependemodulo;
	}

	@Column(name = "ordenmodulo")
	public Integer getOrdenmodulo() {
		return this.ordenmodulo;
	}

	public void setOrdenmodulo(Integer ordenmodulo) {
		this.ordenmodulo = ordenmodulo;
	}

	@Column(name = "flagmodulo")
	public Integer getFlagmodulo() {
		return this.flagmodulo;
	}

	public void setFlagmodulo(Integer flagmodulo) {
		this.flagmodulo = flagmodulo;
	}

	@Column(name = "hrefmodulo", length = 240)
	public String getHrefmodulo() {
		return this.hrefmodulo;
	}

	public void setHrefmodulo(String hrefmodulo) {
		this.hrefmodulo = hrefmodulo;
	}

	@Column(name = "titlemodulo", length = 240)
	public String getTitlemodulo() {
		return this.titlemodulo;
	}

	public void setTitlemodulo(String titlemodulo) {
		this.titlemodulo = titlemodulo;
	}

}
