package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal", schema = "sernanp")
public class Personal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idpersonal;
	private Personanatural personanatural;
	private TAsistenciaTurno TAsistenciaTurno;
	private TEntidadBancaria TEntidadBancaria;
	private TRegimenContractual TRegimenContractual;
	private TRegimenPensionario TRegimenPensionario;
	private String mailpersonal;
	private Integer intCantHijos;
	private Integer intIdProf;
	private Integer intIdNivEdu;
	private Date tspFecCrea;
	private Integer intIdUsuCrea;
	private Date tspFecMod;
	private Integer intIdUsuMod;
	private Integer intEstado;
	private Integer srlIdProfesion;
	private Integer intFlag;
	private String varTarjetaProximidad;
	private Integer srlIdTipoCarrera;
	private String varNumeroCuentaBancaria;
	private String varCodigoAfiliacion;
	private String varNombreAfp;
	private Date dteFechaAfiliacion;
	private Date dteFecIngreso;
	private Integer srlIdAfp;
	private Integer intIdTipoComision;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Personal() {
	}

	public Personal(int idpersonal, Personanatural personanatural) {
		this.idpersonal = idpersonal;
		this.personanatural = personanatural;
	}

	public Personal(int idpersonal, Personanatural personanatural, TAsistenciaTurno TAsistenciaTurno,
			TEntidadBancaria TEntidadBancaria, TRegimenContractual TRegimenContractual,
			TRegimenPensionario TRegimenPensionario, String mailpersonal, Integer intCantHijos, Integer intIdProf,
			Integer intIdNivEdu, Date tspFecCrea, Integer intIdUsuCrea, Date tspFecMod, Integer intIdUsuMod,
			Integer intEstado, Integer srlIdProfesion, Integer intFlag, String varTarjetaProximidad,
			Integer srlIdTipoCarrera, String varNumeroCuentaBancaria, String varCodigoAfiliacion, String varNombreAfp,
			Date dteFechaAfiliacion, Date dteFecIngreso, Integer srlIdAfp, Integer intIdTipoComision,
			Set<Usuario> usuarios) {
		this.idpersonal = idpersonal;
		this.personanatural = personanatural;
		this.TAsistenciaTurno = TAsistenciaTurno;
		this.TEntidadBancaria = TEntidadBancaria;
		this.TRegimenContractual = TRegimenContractual;
		this.TRegimenPensionario = TRegimenPensionario;
		this.mailpersonal = mailpersonal;
		this.intCantHijos = intCantHijos;
		this.intIdProf = intIdProf;
		this.intIdNivEdu = intIdNivEdu;
		this.tspFecCrea = tspFecCrea;
		this.intIdUsuCrea = intIdUsuCrea;
		this.tspFecMod = tspFecMod;
		this.intIdUsuMod = intIdUsuMod;
		this.intEstado = intEstado;
		this.srlIdProfesion = srlIdProfesion;
		this.intFlag = intFlag;
		this.varTarjetaProximidad = varTarjetaProximidad;
		this.srlIdTipoCarrera = srlIdTipoCarrera;
		this.varNumeroCuentaBancaria = varNumeroCuentaBancaria;
		this.varCodigoAfiliacion = varCodigoAfiliacion;
		this.varNombreAfp = varNombreAfp;
		this.dteFechaAfiliacion = dteFechaAfiliacion;
		this.dteFecIngreso = dteFecIngreso;
		this.srlIdAfp = srlIdAfp;
		this.intIdTipoComision = intIdTipoComision;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "idpersonal", unique = true, nullable = false)
	public int getIdpersonal() {
		return this.idpersonal;
	}

	public void setIdpersonal(int idpersonal) {
		this.idpersonal = idpersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersonanatural", nullable = false)
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_asis_turno")
	public TAsistenciaTurno getTAsistenciaTurno() {
		return this.TAsistenciaTurno;
	}

	public void setTAsistenciaTurno(TAsistenciaTurno TAsistenciaTurno) {
		this.TAsistenciaTurno = TAsistenciaTurno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_entidad_bancaria")
	public TEntidadBancaria getTEntidadBancaria() {
		return this.TEntidadBancaria;
	}

	public void setTEntidadBancaria(TEntidadBancaria TEntidadBancaria) {
		this.TEntidadBancaria = TEntidadBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_regimen_contractual")
	public TRegimenContractual getTRegimenContractual() {
		return this.TRegimenContractual;
	}

	public void setTRegimenContractual(TRegimenContractual TRegimenContractual) {
		this.TRegimenContractual = TRegimenContractual;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_regimen_pensionario")
	public TRegimenPensionario getTRegimenPensionario() {
		return this.TRegimenPensionario;
	}

	public void setTRegimenPensionario(TRegimenPensionario TRegimenPensionario) {
		this.TRegimenPensionario = TRegimenPensionario;
	}

	@Column(name = "mailpersonal", length = 250)
	public String getMailpersonal() {
		return this.mailpersonal;
	}

	public void setMailpersonal(String mailpersonal) {
		this.mailpersonal = mailpersonal;
	}

	@Column(name = "int_cant_hijos")
	public Integer getIntCantHijos() {
		return this.intCantHijos;
	}

	public void setIntCantHijos(Integer intCantHijos) {
		this.intCantHijos = intCantHijos;
	}

	@Column(name = "int_id_prof")
	public Integer getIntIdProf() {
		return this.intIdProf;
	}

	public void setIntIdProf(Integer intIdProf) {
		this.intIdProf = intIdProf;
	}

	@Column(name = "int_id_niv_edu")
	public Integer getIntIdNivEdu() {
		return this.intIdNivEdu;
	}

	public void setIntIdNivEdu(Integer intIdNivEdu) {
		this.intIdNivEdu = intIdNivEdu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tsp_fec_crea", length = 29)
	public Date getTspFecCrea() {
		return this.tspFecCrea;
	}

	public void setTspFecCrea(Date tspFecCrea) {
		this.tspFecCrea = tspFecCrea;
	}

	@Column(name = "int_id_usu_crea")
	public Integer getIntIdUsuCrea() {
		return this.intIdUsuCrea;
	}

	public void setIntIdUsuCrea(Integer intIdUsuCrea) {
		this.intIdUsuCrea = intIdUsuCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tsp_fec_mod", length = 29)
	public Date getTspFecMod() {
		return this.tspFecMod;
	}

	public void setTspFecMod(Date tspFecMod) {
		this.tspFecMod = tspFecMod;
	}

	@Column(name = "int_id_usu_mod")
	public Integer getIntIdUsuMod() {
		return this.intIdUsuMod;
	}

	public void setIntIdUsuMod(Integer intIdUsuMod) {
		this.intIdUsuMod = intIdUsuMod;
	}

	@Column(name = "int_estado")
	public Integer getIntEstado() {
		return this.intEstado;
	}

	public void setIntEstado(Integer intEstado) {
		this.intEstado = intEstado;
	}

	@Column(name = "srl_id_profesion")
	public Integer getSrlIdProfesion() {
		return this.srlIdProfesion;
	}

	public void setSrlIdProfesion(Integer srlIdProfesion) {
		this.srlIdProfesion = srlIdProfesion;
	}

	@Column(name = "int_flag")
	public Integer getIntFlag() {
		return this.intFlag;
	}

	public void setIntFlag(Integer intFlag) {
		this.intFlag = intFlag;
	}

	@Column(name = "var_tarjeta_proximidad", length = 50)
	public String getVarTarjetaProximidad() {
		return this.varTarjetaProximidad;
	}

	public void setVarTarjetaProximidad(String varTarjetaProximidad) {
		this.varTarjetaProximidad = varTarjetaProximidad;
	}

	@Column(name = "srl_id_tipo_carrera")
	public Integer getSrlIdTipoCarrera() {
		return this.srlIdTipoCarrera;
	}

	public void setSrlIdTipoCarrera(Integer srlIdTipoCarrera) {
		this.srlIdTipoCarrera = srlIdTipoCarrera;
	}

	@Column(name = "var_numero_cuenta_bancaria", length = 50)
	public String getVarNumeroCuentaBancaria() {
		return this.varNumeroCuentaBancaria;
	}

	public void setVarNumeroCuentaBancaria(String varNumeroCuentaBancaria) {
		this.varNumeroCuentaBancaria = varNumeroCuentaBancaria;
	}

	@Column(name = "var_codigo_afiliacion", length = 20)
	public String getVarCodigoAfiliacion() {
		return this.varCodigoAfiliacion;
	}

	public void setVarCodigoAfiliacion(String varCodigoAfiliacion) {
		this.varCodigoAfiliacion = varCodigoAfiliacion;
	}

	@Column(name = "var_nombre_afp", length = 50)
	public String getVarNombreAfp() {
		return this.varNombreAfp;
	}

	public void setVarNombreAfp(String varNombreAfp) {
		this.varNombreAfp = varNombreAfp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fecha_afiliacion", length = 13)
	public Date getDteFechaAfiliacion() {
		return this.dteFechaAfiliacion;
	}

	public void setDteFechaAfiliacion(Date dteFechaAfiliacion) {
		this.dteFechaAfiliacion = dteFechaAfiliacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_ingreso", length = 13)
	public Date getDteFecIngreso() {
		return this.dteFecIngreso;
	}

	public void setDteFecIngreso(Date dteFecIngreso) {
		this.dteFecIngreso = dteFecIngreso;
	}

	@Column(name = "srl_id_afp")
	public Integer getSrlIdAfp() {
		return this.srlIdAfp;
	}

	public void setSrlIdAfp(Integer srlIdAfp) {
		this.srlIdAfp = srlIdAfp;
	}

	@Column(name = "int_id_tipo_comision")
	public Integer getIntIdTipoComision() {
		return this.intIdTipoComision;
	}

	public void setIntIdTipoComision(Integer intIdTipoComision) {
		this.intIdTipoComision = intIdTipoComision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
