package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personanatural generated by hbm2java
 */
@Entity
@Table(name = "personanatural", schema = "sernanp")
public class Personanatural implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idpersonanatural;
	private Persona persona;
	private Tablatipo tablatipoByIdsexo;
	private Tablatipo tablatipoByIdestadocivil;
	private Tablatipo tablatipoByIdtipodocumento;
	private Ubigeo ubigeo;
	private String nombre;
	private String apepat;
	private String apemat;
	private String numerodoc;
	private Date fechanacimiento;
	private Integer temporal;
	private String ruc;
	private String direccion;
	private String varNumFile;
	private String varNumCaja;
	private String varNumeroPasaporte;
	private String varNumeroBrevete;
	private Integer intIdTipo;
	private Set<Personal> personals = new HashSet<Personal>(0);

	public Personanatural() {
	}

	public Personanatural(int idpersonanatural, Persona persona) {
		this.idpersonanatural = idpersonanatural;
		this.persona = persona;
	}

	public Personanatural(int idpersonanatural, Persona persona, Tablatipo tablatipoByIdsexo,
			Tablatipo tablatipoByIdestadocivil, Tablatipo tablatipoByIdtipodocumento, Ubigeo ubigeo, String nombre,
			String apepat, String apemat, String numerodoc, Date fechanacimiento, Integer temporal, String ruc,
			String direccion, String varNumFile, String varNumCaja, String varNumeroPasaporte, String varNumeroBrevete,
			Integer intIdTipo, Set<Personal> personals) {
		this.idpersonanatural = idpersonanatural;
		this.persona = persona;
		this.tablatipoByIdsexo = tablatipoByIdsexo;
		this.tablatipoByIdestadocivil = tablatipoByIdestadocivil;
		this.tablatipoByIdtipodocumento = tablatipoByIdtipodocumento;
		this.ubigeo = ubigeo;
		this.nombre = nombre;
		this.apepat = apepat;
		this.apemat = apemat;
		this.numerodoc = numerodoc;
		this.fechanacimiento = fechanacimiento;
		this.temporal = temporal;
		this.ruc = ruc;
		this.direccion = direccion;
		this.varNumFile = varNumFile;
		this.varNumCaja = varNumCaja;
		this.varNumeroPasaporte = varNumeroPasaporte;
		this.varNumeroBrevete = varNumeroBrevete;
		this.intIdTipo = intIdTipo;
		this.personals = personals;
	}

	@Id
	@Column(name = "idpersonanatural", unique = true, nullable = false)
	public int getIdpersonanatural() {
		return this.idpersonanatural;
	}

	public void setIdpersonanatural(int idpersonanatural) {
		this.idpersonanatural = idpersonanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsexo")
	public Tablatipo getTablatipoByIdsexo() {
		return this.tablatipoByIdsexo;
	}

	public void setTablatipoByIdsexo(Tablatipo tablatipoByIdsexo) {
		this.tablatipoByIdsexo = tablatipoByIdsexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocivil")
	public Tablatipo getTablatipoByIdestadocivil() {
		return this.tablatipoByIdestadocivil;
	}

	public void setTablatipoByIdestadocivil(Tablatipo tablatipoByIdestadocivil) {
		this.tablatipoByIdestadocivil = tablatipoByIdestadocivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipodocumento")
	public Tablatipo getTablatipoByIdtipodocumento() {
		return this.tablatipoByIdtipodocumento;
	}

	public void setTablatipoByIdtipodocumento(Tablatipo tablatipoByIdtipodocumento) {
		this.tablatipoByIdtipodocumento = tablatipoByIdtipodocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idubigeo")
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apepat", length = 45)
	public String getApepat() {
		return this.apepat;
	}

	public void setApepat(String apepat) {
		this.apepat = apepat;
	}

	@Column(name = "apemat", length = 45)
	public String getApemat() {
		return this.apemat;
	}

	public void setApemat(String apemat) {
		this.apemat = apemat;
	}

	@Column(name = "numerodoc", length = 45)
	public String getNumerodoc() {
		return this.numerodoc;
	}

	public void setNumerodoc(String numerodoc) {
		this.numerodoc = numerodoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanacimiento", length = 13)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "temporal")
	public Integer getTemporal() {
		return this.temporal;
	}

	public void setTemporal(Integer temporal) {
		this.temporal = temporal;
	}

	@Column(name = "ruc", length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "direccion", length = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "var_num_file", length = 100)
	public String getVarNumFile() {
		return this.varNumFile;
	}

	public void setVarNumFile(String varNumFile) {
		this.varNumFile = varNumFile;
	}

	@Column(name = "var_num_caja", length = 100)
	public String getVarNumCaja() {
		return this.varNumCaja;
	}

	public void setVarNumCaja(String varNumCaja) {
		this.varNumCaja = varNumCaja;
	}

	@Column(name = "var_numero_pasaporte", length = 20)
	public String getVarNumeroPasaporte() {
		return this.varNumeroPasaporte;
	}

	public void setVarNumeroPasaporte(String varNumeroPasaporte) {
		this.varNumeroPasaporte = varNumeroPasaporte;
	}

	@Column(name = "var_numero_brevete", length = 20)
	public String getVarNumeroBrevete() {
		return this.varNumeroBrevete;
	}

	public void setVarNumeroBrevete(String varNumeroBrevete) {
		this.varNumeroBrevete = varNumeroBrevete;
	}

	@Column(name = "int_id_tipo")
	public Integer getIntIdTipo() {
		return this.intIdTipo;
	}

	public void setIntIdTipo(Integer intIdTipo) {
		this.intIdTipo = intIdTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Set<Personal> getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set<Personal> personals) {
		this.personals = personals;
	}

}
