package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "sernanp")
public class Persona implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idpersona;
	private Pais pais;
	private Ubigeo ubigeo;
	private String direccion;
	private String telefono;
	private String correopersonal;
	private String correoinstitucional;
	private String ruc;
	private Integer temporal;
	private Set<Personanatural> personanaturals = new HashSet<Personanatural>(0);

	public Persona() {
	}

	public Persona(int idpersona) {
		this.idpersona = idpersona;
	}

	public Persona(int idpersona, Pais pais, Ubigeo ubigeo, String direccion, String telefono, String correopersonal,
			String correoinstitucional, String ruc, Integer temporal, Set<Personanatural> personanaturals) {
		this.idpersona = idpersona;
		this.pais = pais;
		this.ubigeo = ubigeo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correopersonal = correopersonal;
		this.correoinstitucional = correoinstitucional;
		this.ruc = ruc;
		this.temporal = temporal;
		this.personanaturals = personanaturals;
	}

	@Id
	@Column(name = "idpersona", unique = true, nullable = false)
	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpais")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idubigeo")
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "direccion", length = 250)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 32)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correopersonal", length = 100)
	public String getCorreopersonal() {
		return this.correopersonal;
	}

	public void setCorreopersonal(String correopersonal) {
		this.correopersonal = correopersonal;
	}

	@Column(name = "correoinstitucional", length = 100)
	public String getCorreoinstitucional() {
		return this.correoinstitucional;
	}

	public void setCorreoinstitucional(String correoinstitucional) {
		this.correoinstitucional = correoinstitucional;
	}

	@Column(name = "ruc", length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "temporal")
	public Integer getTemporal() {
		return this.temporal;
	}

	public void setTemporal(Integer temporal) {
		this.temporal = temporal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Personanatural> getPersonanaturals() {
		return this.personanaturals;
	}

	public void setPersonanaturals(Set<Personanatural> personanaturals) {
		this.personanaturals = personanaturals;
	}

}
