package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import pe.com.mig.model.entity.sde.TbtRegistroNac;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede", schema = "sernanp")
public class Sede implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idsede;
	private Areanatural areanatural;
	private Sede sede;
	private Ubigeo ubigeo;
	private TbtRegistroNac registronac;
	private String dessede;
	private String direccion;
	private Integer intSedePrincipal;
	private Set<Areaorganica> areaorganicas = new HashSet<Areaorganica>(0);
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Sede() {
	}

	public Sede(int idsede, Ubigeo ubigeo) {
		this.idsede = idsede;
		this.ubigeo = ubigeo;
	}

	public Sede(int idsede, Areanatural areanatural, Sede sede, Ubigeo ubigeo, String dessede, String direccion,
			Integer intSedePrincipal, Set<Areaorganica> areaorganicas, Set<Sede> sedes) {
		this.idsede = idsede;
		this.areanatural = areanatural;
		this.sede = sede;
		this.ubigeo = ubigeo;
		this.dessede = dessede;
		this.direccion = direccion;
		this.intSedePrincipal = intSedePrincipal;
		this.areaorganicas = areaorganicas;
		this.sedes = sedes;
	}

	@Id
	@Column(name = "idsede", unique = true, nullable = false)
	public int getIdsede() {
		return this.idsede;
	}

	public void setIdsede(int idsede) {
		this.idsede = idsede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idareanatural")
	public Areanatural getAreanatural() {
		return this.areanatural;
	}

	public void setAreanatural(Areanatural areanatural) {
		this.areanatural = areanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsedeprincipal")
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idubigeo", nullable = false)
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ranac")
	public TbtRegistroNac getRegistronac() {
		return this.registronac;
	}

	public void setRegistronac(TbtRegistroNac registronac) {
		this.registronac = registronac;
	}

	@Column(name = "dessede", length = 45)
	public String getDessede() {
		return this.dessede;
	}

	public void setDessede(String dessede) {
		this.dessede = dessede;
	}

	@Column(name = "direccion", length = 128)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "int_sede_principal")
	public Integer getIntSedePrincipal() {
		return this.intSedePrincipal;
	}

	public void setIntSedePrincipal(Integer intSedePrincipal) {
		this.intSedePrincipal = intSedePrincipal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<Areaorganica> getAreaorganicas() {
		return this.areaorganicas;
	}

	public void setAreaorganicas(Set<Areaorganica> areaorganicas) {
		this.areaorganicas = areaorganicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
