package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", schema = "sernanp")
public class Sistema implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idsistema;
	private Integer idmodulo;
	private String dessistema;
	private String siglas;
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<TUsuarioFtp> TUsuarioFtps = new HashSet<TUsuarioFtp>(0);
	private Set<Login> logins = new HashSet<Login>(0);

	public Sistema() {
	}

	public Sistema(int idsistema) {
		this.idsistema = idsistema;
	}

	public Sistema(int idsistema, Integer idmodulo, String dessistema, String siglas, Set<Rol> rols,
			Set<TUsuarioFtp> TUsuarioFtps, Set<Login> logins) {
		this.idsistema = idsistema;
		this.idmodulo = idmodulo;
		this.dessistema = dessistema;
		this.siglas = siglas;
		this.rols = rols;
		this.TUsuarioFtps = TUsuarioFtps;
		this.logins = logins;
	}

	@Id
	@Column(name = "idsistema", unique = true, nullable = false)
	public int getIdsistema() {
		return this.idsistema;
	}

	public void setIdsistema(int idsistema) {
		this.idsistema = idsistema;
	}

	@Column(name = "idmodulo")
	public Integer getIdmodulo() {
		return this.idmodulo;
	}

	public void setIdmodulo(Integer idmodulo) {
		this.idmodulo = idmodulo;
	}

	@Column(name = "dessistema", length = 200)
	public String getDessistema() {
		return this.dessistema;
	}

	public void setDessistema(String dessistema) {
		this.dessistema = dessistema;
	}

	@Column(name = "siglas", length = 10)
	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<TUsuarioFtp> getTUsuarioFtps() {
		return this.TUsuarioFtps;
	}

	public void setTUsuarioFtps(Set<TUsuarioFtp> TUsuarioFtps) {
		this.TUsuarioFtps = TUsuarioFtps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

}
