package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tabla generated by hbm2java
 */
@Entity
@Table(name = "tabla", schema = "sernanp")
public class Tabla implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idtabla;
	private String destabla;
	private Set<Tablatipo> tablatipos = new HashSet<Tablatipo>(0);

	public Tabla() {
	}

	public Tabla(int idtabla) {
		this.idtabla = idtabla;
	}

	public Tabla(int idtabla, String destabla, Set<Tablatipo> tablatipos) {
		this.idtabla = idtabla;
		this.destabla = destabla;
		this.tablatipos = tablatipos;
	}

	@Id
	@Column(name = "idtabla", unique = true, nullable = false)
	public int getIdtabla() {
		return this.idtabla;
	}

	public void setIdtabla(int idtabla) {
		this.idtabla = idtabla;
	}

	@Column(name = "destabla", length = 45)
	public String getDestabla() {
		return this.destabla;
	}

	public void setDestabla(String destabla) {
		this.destabla = destabla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tabla")
	public Set<Tablatipo> getTablatipos() {
		return this.tablatipos;
	}

	public void setTablatipos(Set<Tablatipo> tablatipos) {
		this.tablatipos = tablatipos;
	}

}
