package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tablatipo generated by hbm2java
 */
@Entity
@Table(name = "tablatipo", schema = "sernanp")
public class Tablatipo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idtablatipo;
	private Tabla tabla;
	private Integer ordtablatipo;
	private String destablatipo;
	private String abrtablatipo;
	private Integer codinttablatipo;
	private String mensajetablatipo;
	private String clasetablatipo;
	private Integer flagvisible;
	private Integer intCodReferTablatipo;
	private Set<Areaorganica> areaorganicas = new HashSet<Areaorganica>(0);
	private Set<Personanatural> personanaturalsForIdsexo = new HashSet<Personanatural>(0);
	private Set<Personanatural> personanaturalsForIdestadocivil = new HashSet<Personanatural>(0);
	private Set<Personanatural> personanaturalsForIdtipodocumento = new HashSet<Personanatural>(0);

	public Tablatipo() {
	}

	public Tablatipo(int idtablatipo, Tabla tabla) {
		this.idtablatipo = idtablatipo;
		this.tabla = tabla;
	}

	public Tablatipo(int idtablatipo, Tabla tabla, Integer ordtablatipo, String destablatipo, String abrtablatipo,
			Integer codinttablatipo, String mensajetablatipo, String clasetablatipo, Integer flagvisible,
			Integer intCodReferTablatipo, Set<Areaorganica> areaorganicas, Set<Personanatural> personanaturalsForIdsexo,
			Set<Personanatural> personanaturalsForIdestadocivil,
			Set<Personanatural> personanaturalsForIdtipodocumento) {
		this.idtablatipo = idtablatipo;
		this.tabla = tabla;
		this.ordtablatipo = ordtablatipo;
		this.destablatipo = destablatipo;
		this.abrtablatipo = abrtablatipo;
		this.codinttablatipo = codinttablatipo;
		this.mensajetablatipo = mensajetablatipo;
		this.clasetablatipo = clasetablatipo;
		this.flagvisible = flagvisible;
		this.intCodReferTablatipo = intCodReferTablatipo;
		this.areaorganicas = areaorganicas;
		this.personanaturalsForIdsexo = personanaturalsForIdsexo;
		this.personanaturalsForIdestadocivil = personanaturalsForIdestadocivil;
		this.personanaturalsForIdtipodocumento = personanaturalsForIdtipodocumento;
	}

	@Id
	@Column(name = "idtablatipo", unique = true, nullable = false)
	public int getIdtablatipo() {
		return this.idtablatipo;
	}

	public void setIdtablatipo(int idtablatipo) {
		this.idtablatipo = idtablatipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtabla", nullable = false)
	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	@Column(name = "ordtablatipo")
	public Integer getOrdtablatipo() {
		return this.ordtablatipo;
	}

	public void setOrdtablatipo(Integer ordtablatipo) {
		this.ordtablatipo = ordtablatipo;
	}

	@Column(name = "destablatipo", length = 200)
	public String getDestablatipo() {
		return this.destablatipo;
	}

	public void setDestablatipo(String destablatipo) {
		this.destablatipo = destablatipo;
	}

	@Column(name = "abrtablatipo", length = 45)
	public String getAbrtablatipo() {
		return this.abrtablatipo;
	}

	public void setAbrtablatipo(String abrtablatipo) {
		this.abrtablatipo = abrtablatipo;
	}

	@Column(name = "codinttablatipo")
	public Integer getCodinttablatipo() {
		return this.codinttablatipo;
	}

	public void setCodinttablatipo(Integer codinttablatipo) {
		this.codinttablatipo = codinttablatipo;
	}

	@Column(name = "mensajetablatipo", length = 100)
	public String getMensajetablatipo() {
		return this.mensajetablatipo;
	}

	public void setMensajetablatipo(String mensajetablatipo) {
		this.mensajetablatipo = mensajetablatipo;
	}

	@Column(name = "clasetablatipo", length = 40)
	public String getClasetablatipo() {
		return this.clasetablatipo;
	}

	public void setClasetablatipo(String clasetablatipo) {
		this.clasetablatipo = clasetablatipo;
	}

	@Column(name = "flagvisible")
	public Integer getFlagvisible() {
		return this.flagvisible;
	}

	public void setFlagvisible(Integer flagvisible) {
		this.flagvisible = flagvisible;
	}

	@Column(name = "int_cod_refer_tablatipo")
	public Integer getIntCodReferTablatipo() {
		return this.intCodReferTablatipo;
	}

	public void setIntCodReferTablatipo(Integer intCodReferTablatipo) {
		this.intCodReferTablatipo = intCodReferTablatipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tablatipo")
	public Set<Areaorganica> getAreaorganicas() {
		return this.areaorganicas;
	}

	public void setAreaorganicas(Set<Areaorganica> areaorganicas) {
		this.areaorganicas = areaorganicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tablatipoByIdsexo")
	public Set<Personanatural> getPersonanaturalsForIdsexo() {
		return this.personanaturalsForIdsexo;
	}

	public void setPersonanaturalsForIdsexo(Set<Personanatural> personanaturalsForIdsexo) {
		this.personanaturalsForIdsexo = personanaturalsForIdsexo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tablatipoByIdestadocivil")
	public Set<Personanatural> getPersonanaturalsForIdestadocivil() {
		return this.personanaturalsForIdestadocivil;
	}

	public void setPersonanaturalsForIdestadocivil(Set<Personanatural> personanaturalsForIdestadocivil) {
		this.personanaturalsForIdestadocivil = personanaturalsForIdestadocivil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tablatipoByIdtipodocumento")
	public Set<Personanatural> getPersonanaturalsForIdtipodocumento() {
		return this.personanaturalsForIdtipodocumento;
	}

	public void setPersonanaturalsForIdtipodocumento(Set<Personanatural> personanaturalsForIdtipodocumento) {
		this.personanaturalsForIdtipodocumento = personanaturalsForIdtipodocumento;
	}

}
