package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEntidadBancaria generated by hbm2java
 */
@Entity
@Table(name = "t_entidad_bancaria", schema = "sernanp")
public class TEntidadBancaria implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdEntidadBancaria;
	private String varDescEntidadBancaria;
	private Integer intEntidadBancaria;
	private Set<Personal> personals = new HashSet<Personal>(0);
	private Set<Personal> personals_1 = new HashSet<Personal>(0);

	public TEntidadBancaria() {
	}

	public TEntidadBancaria(int srlIdEntidadBancaria, String varDescEntidadBancaria) {
		this.srlIdEntidadBancaria = srlIdEntidadBancaria;
		this.varDescEntidadBancaria = varDescEntidadBancaria;
	}

	public TEntidadBancaria(int srlIdEntidadBancaria, String varDescEntidadBancaria, Integer intEntidadBancaria,
			Set<Personal> personals, Set<Personal> personals_1) {
		this.srlIdEntidadBancaria = srlIdEntidadBancaria;
		this.varDescEntidadBancaria = varDescEntidadBancaria;
		this.intEntidadBancaria = intEntidadBancaria;
		this.personals = personals;
		this.personals_1 = personals_1;
	}

	@Id
	@Column(name = "srl_id_entidad_bancaria", unique = true, nullable = false)
	public int getSrlIdEntidadBancaria() {
		return this.srlIdEntidadBancaria;
	}

	public void setSrlIdEntidadBancaria(int srlIdEntidadBancaria) {
		this.srlIdEntidadBancaria = srlIdEntidadBancaria;
	}

	@Column(name = "var_desc_entidad_bancaria", nullable = false, length = 100)
	public String getVarDescEntidadBancaria() {
		return this.varDescEntidadBancaria;
	}

	public void setVarDescEntidadBancaria(String varDescEntidadBancaria) {
		this.varDescEntidadBancaria = varDescEntidadBancaria;
	}

	@Column(name = "int_entidad_bancaria")
	public Integer getIntEntidadBancaria() {
		return this.intEntidadBancaria;
	}

	public void setIntEntidadBancaria(Integer intEntidadBancaria) {
		this.intEntidadBancaria = intEntidadBancaria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEntidadBancaria")
	public Set<Personal> getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set<Personal> personals) {
		this.personals = personals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEntidadBancaria")
	public Set<Personal> getPersonals_1() {
		return this.personals_1;
	}

	public void setPersonals_1(Set<Personal> personals_1) {
		this.personals_1 = personals_1;
	}

}
