package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRegimenPensionario generated by hbm2java
 */
@Entity
@Table(name = "t_regimen_pensionario", schema = "sernanp")
public class TRegimenPensionario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdRegimenPensionario;
	private TRegimenContractual TRegimenContractual;
	private Integer intCodRegimenPensionario;
	private String varDescripcionRegimenPensionario;
	private Set<Personal> personals = new HashSet<Personal>(0);

	public TRegimenPensionario() {
	}

	public TRegimenPensionario(int srlIdRegimenPensionario, TRegimenContractual TRegimenContractual,
			String varDescripcionRegimenPensionario) {
		this.srlIdRegimenPensionario = srlIdRegimenPensionario;
		this.TRegimenContractual = TRegimenContractual;
		this.varDescripcionRegimenPensionario = varDescripcionRegimenPensionario;
	}

	public TRegimenPensionario(int srlIdRegimenPensionario, TRegimenContractual TRegimenContractual,
			Integer intCodRegimenPensionario, String varDescripcionRegimenPensionario, Set<Personal> personals) {
		this.srlIdRegimenPensionario = srlIdRegimenPensionario;
		this.TRegimenContractual = TRegimenContractual;
		this.intCodRegimenPensionario = intCodRegimenPensionario;
		this.varDescripcionRegimenPensionario = varDescripcionRegimenPensionario;
		this.personals = personals;
	}

	@Id
	@Column(name = "srl_id_regimen_pensionario", unique = true, nullable = false)
	public int getSrlIdRegimenPensionario() {
		return this.srlIdRegimenPensionario;
	}

	public void setSrlIdRegimenPensionario(int srlIdRegimenPensionario) {
		this.srlIdRegimenPensionario = srlIdRegimenPensionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_regimen_contractual", nullable = false)
	public TRegimenContractual getTRegimenContractual() {
		return this.TRegimenContractual;
	}

	public void setTRegimenContractual(TRegimenContractual TRegimenContractual) {
		this.TRegimenContractual = TRegimenContractual;
	}

	@Column(name = "int_cod_regimen_pensionario")
	public Integer getIntCodRegimenPensionario() {
		return this.intCodRegimenPensionario;
	}

	public void setIntCodRegimenPensionario(Integer intCodRegimenPensionario) {
		this.intCodRegimenPensionario = intCodRegimenPensionario;
	}

	@Column(name = "var_descripcion_regimen_pensionario", nullable = false, length = 100)
	public String getVarDescripcionRegimenPensionario() {
		return this.varDescripcionRegimenPensionario;
	}

	public void setVarDescripcionRegimenPensionario(String varDescripcionRegimenPensionario) {
		this.varDescripcionRegimenPensionario = varDescripcionRegimenPensionario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRegimenPensionario")
	public Set<Personal> getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set<Personal> personals) {
		this.personals = personals;
	}

}
