package pe.com.mig.model.entity.sernanp;
// Generated 22/06/2016 10:33:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUnidadoperativaAnpAdm generated by hbm2java
 */
@Entity
@Table(name = "t_unidadoperativa_anp_adm", schema = "sernanp")
public class TUnidadoperativaAnpAdm implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdAdm;
	private Integer idunidad;
	private long idRanac;
	private int intEstado;

	public TUnidadoperativaAnpAdm() {
	}
	
	public TUnidadoperativaAnpAdm(int srlIdAdm) {
		this.srlIdAdm = srlIdAdm;
	}

	public TUnidadoperativaAnpAdm(int srlIdAdm, long idRanac, int intEstado) {
		this.srlIdAdm = srlIdAdm;
		this.idRanac = idRanac;
		this.intEstado = intEstado;
	}

	public TUnidadoperativaAnpAdm(int srlIdAdm, Integer idunidad, long idRanac, int intEstado) {
		this.srlIdAdm = srlIdAdm;
		this.idunidad = idunidad;
		this.idRanac = idRanac;
		this.intEstado = intEstado;
	}

	@Id
	@Column(name = "srl_id_adm", unique = true, nullable = false)
	public int getSrlIdAdm() {
		return this.srlIdAdm;
	}

	public void setSrlIdAdm(int srlIdAdm) {
		this.srlIdAdm = srlIdAdm;
	}

	@Column(name = "idunidad")
	public Integer getIdunidad() {
		return this.idunidad;
	}

	public void setIdunidad(Integer idunidad) {
		this.idunidad = idunidad;
	}

	@Column(name = "id_ranac", nullable = false)
	public long getIdRanac() {
		return this.idRanac;
	}

	public void setIdRanac(long idRanac) {
		this.idRanac = idRanac;
	}

	@Column(name = "int_estado", nullable = false)
	public int getIntEstado() {
		return this.intEstado;
	}

	public void setIntEstado(int intEstado) {
		this.intEstado = intEstado;
	}

}
