package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name = "ubigeo", schema = "sernanp")
public class Ubigeo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idubigeo;
	private String coddpto;
	private String codprov;
	private String coddist;
	private String nombre;
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<Sede> sedes = new HashSet<Sede>(0);
	private Set<Personanatural> personanaturals = new HashSet<Personanatural>(0);

	public Ubigeo() {
	}

	public Ubigeo(int idubigeo) {
		this.idubigeo = idubigeo;
	}

	public Ubigeo(int idubigeo, String coddpto, String codprov, String coddist, String nombre, Set<Persona> personas,
			Set<Sede> sedes, Set<Personanatural> personanaturals) {
		this.idubigeo = idubigeo;
		this.coddpto = coddpto;
		this.codprov = codprov;
		this.coddist = coddist;
		this.nombre = nombre;
		this.personas = personas;
		this.sedes = sedes;
		this.personanaturals = personanaturals;
	}

	@Id
	@Column(name = "idubigeo", unique = true, nullable = false)
	public int getIdubigeo() {
		return this.idubigeo;
	}

	public void setIdubigeo(int idubigeo) {
		this.idubigeo = idubigeo;
	}

	@Column(name = "coddpto", length = 2)
	public String getCoddpto() {
		return this.coddpto;
	}

	public void setCoddpto(String coddpto) {
		this.coddpto = coddpto;
	}

	@Column(name = "codprov", length = 2)
	public String getCodprov() {
		return this.codprov;
	}

	public void setCodprov(String codprov) {
		this.codprov = codprov;
	}

	@Column(name = "coddist", length = 2)
	public String getCoddist() {
		return this.coddist;
	}

	public void setCoddist(String coddist) {
		this.coddist = coddist;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set<Personanatural> getPersonanaturals() {
		return this.personanaturals;
	}

	public void setPersonanaturals(Set<Personanatural> personanaturals) {
		this.personanaturals = personanaturals;
	}

}
