package pe.com.mig.model.entity.sernanp;
// Generated 22/06/2016 09:09:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Unidadoperativa generated by hbm2java
 */
@Entity
@Table(name = "unidadoperativa", schema = "sernanp")
public class Unidadoperativa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idunidad;
	private Areaorganica areaorganica;
	private String nomunidad;

	public Unidadoperativa() {
	}
	
	public Unidadoperativa(int idunidad) {
		this.idunidad = idunidad;
	}

	public Unidadoperativa(int idunidad, Areaorganica areaorganica) {
		this.idunidad = idunidad;
		this.areaorganica = areaorganica;
	}

	public Unidadoperativa(int idunidad, Areaorganica areaorganica, String nomunidad) {
		this.idunidad = idunidad;
		this.areaorganica = areaorganica;
		this.nomunidad = nomunidad;
	}

	@Id
	@Column(name = "idunidad", unique = true, nullable = false)
	public int getIdunidad() {
		return this.idunidad;
	}

	public void setIdunidad(int idunidad) {
		this.idunidad = idunidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idarea", nullable = false)
	public Areaorganica getAreaorganica() {
		return this.areaorganica;
	}

	public void setAreaorganica(Areaorganica areaorganica) {
		this.areaorganica = areaorganica;
	}

	@Column(name = "nomunidad", length = 200)
	public String getNomunidad() {
		return this.nomunidad;
	}

	public void setNomunidad(String nomunidad) {
		this.nomunidad = nomunidad;
	}

}
