package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "sernanp")
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idusuario;
	private Areaorganica areaorganica;
	private Personal personal;
	private Rol rol;
	private String usuario;
	private String clave;
	private Integer estado;
	private Integer loginfirst;
	private Integer idpersona;
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<TUsuarioFtp> TUsuarioFtps = new HashSet<TUsuarioFtp>(0);
	private Set<Login> logins = new HashSet<Login>(0);

	public Usuario() {
	}

	public Usuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public Usuario(int idusuario, Areaorganica areaorganica, Personal personal, Rol rol, String usuario, String clave,
			Integer estado, Integer loginfirst, Integer idpersona, Set<Rol> rols, Set<TUsuarioFtp> TUsuarioFtps,
			Set<Login> logins) {
		this.idusuario = idusuario;
		this.areaorganica = areaorganica;
		this.personal = personal;
		this.rol = rol;
		this.usuario = usuario;
		this.clave = clave;
		this.estado = estado;
		this.loginfirst = loginfirst;
		this.idpersona = idpersona;
		this.rols = rols;
		this.TUsuarioFtps = TUsuarioFtps;
		this.logins = logins;
	}

	@Id
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idarea")
	public Areaorganica getAreaorganica() {
		return this.areaorganica;
	}

	public void setAreaorganica(Areaorganica areaorganica) {
		this.areaorganica = areaorganica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersonal")
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "usuario", length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", length = 200)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "loginfirst")
	public Integer getLoginfirst() {
		return this.loginfirst;
	}

	public void setLoginfirst(Integer loginfirst) {
		this.loginfirst = loginfirst;
	}

	@Column(name = "idpersona")
	public Integer getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<TUsuarioFtp> getTUsuarioFtps() {
		return this.TUsuarioFtps;
	}

	public void setTUsuarioFtps(Set<TUsuarioFtp> TUsuarioFtps) {
		this.TUsuarioFtps = TUsuarioFtps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

}
