package pe.com.mig.model.entity.sernanp;
// Generated 16/06/2016 12:59:06 AM by Hibernate Tools 4.3.1

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "usuariorol", schema = "sernanp")
public class UsuarioRol implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    private UsuarioRolPK usuarioRolPK;

	@EmbeddedId
	public UsuarioRolPK getUsuarioRolPK() {
		return this.usuarioRolPK;
	}

	public void setUsuarioRolPK(UsuarioRolPK usuarioRolPK) {
		this.usuarioRolPK = usuarioRolPK;
	}

}
