package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.com.mig.model.entity.sde.TbtRegistroNac;
import pe.com.mig.model.entity.sernanp.Unidadoperativa;

/**
 * TCierreMes generated by hbm2java
 */
@Entity
@Table(name = "t_cierre_mes", schema = "mig")
public class TCierreMesA implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdMes;
	private Integer intAno;
	private Integer intMes;
	private Date dteFecCierre;
	private Date dteFecDescierre;
	private Date dteFecApertura;
	private String chrMesActivo;
	private String chrFlgApertura;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Integer intUnidad;
	private Integer srlIdAdm;

	public TCierreMesA() {
	}

	public TCierreMesA(int srlIdMes) {
		this.srlIdMes = srlIdMes;
	}
	
	

	public TCierreMesA(int srlIdMes, Integer intAno, Integer intMes, Date dteFecCierre, Date dteFecDescierre,
			Date dteFecApertura, String chrMesActivo, String chrFlgApertura, Integer intUnidad, Integer srlIdAdm,String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica ) {
		this.srlIdMes = srlIdMes;
		this.intAno = intAno;
		this.intMes = intMes;
		this.dteFecCierre = dteFecCierre;
		this.dteFecDescierre = dteFecDescierre;
		this.dteFecApertura = dteFecApertura;
		this.chrMesActivo = chrMesActivo;
		this.chrFlgApertura = chrFlgApertura;
		this.intUnidad = intUnidad;
		this.srlIdAdm = srlIdAdm;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_cierre_mes", sequenceName = "mig.t_cierre_mes_srl_id_mes_seq")
	@GeneratedValue(generator = "seq_cierre_mes")
	@Column(name = "srl_id_mes", unique = true, nullable = false)
	public int getSrlIdMes() {
		return this.srlIdMes;
	}

	public void setSrlIdMes(int srlIdMes) {
		this.srlIdMes = srlIdMes;
	}

	@Column(name = "int_ano")
	public Integer getIntAno() {
		return this.intAno;
	}

	public void setIntAno(Integer intAno) {
		this.intAno = intAno;
	}

	@Column(name = "int_mes")
	public Integer getIntMes() {
		return this.intMes;
	}

	public void setIntMes(Integer intMes) {
		this.intMes = intMes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_cierre", length = 13)
	public Date getDteFecCierre() {
		return this.dteFecCierre;
	}

	public void setDteFecCierre(Date dteFecCierre) {
		this.dteFecCierre = dteFecCierre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_descierre", length = 13)
	public Date getDteFecDescierre() {
		return this.dteFecDescierre;
	}

	public void setDteFecDescierre(Date dteFecDescierre) {
		this.dteFecDescierre = dteFecDescierre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_apertura", length = 13)
	public Date getDteFecApertura() {
		return this.dteFecApertura;
	}

	public void setDteFecApertura(Date dteFecApertura) {
		this.dteFecApertura = dteFecApertura;
	}

	@Column(name = "chr_mes_activo", length = 1)
	public String getChrMesActivo() {
		return this.chrMesActivo;
	}

	public void setChrMesActivo(String chrMesActivo) {
		this.chrMesActivo = chrMesActivo;
	}

	@Column(name = "chr_flg_apertura", length = 1)
	public String getChrFlgApertura() {
		return this.chrFlgApertura;
	}

	public void setChrFlgApertura(String chrFlgApertura) {
		this.chrFlgApertura = chrFlgApertura;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	/**
	 * @return the intUnidad
	 */
	@Column(name = "idunidad")
	public Integer getIntUnidad() {
		return intUnidad;
	}

	/**
	 * @param intUnidad the intUnidad to set
	 */
	public void setIntUnidad(Integer intUnidad) {
		this.intUnidad = intUnidad;
	}

	@Column(name = "srl_id_adm")
	public Integer getSrlIdAdm() {
		return srlIdAdm;
	}

	public void setSrlIdAdm(Integer srlIdAdm) {
		this.srlIdAdm = srlIdAdm;
	}

}
