package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TComprobanteCuarta generated by hbm2java
 */
@Entity
@Table(name = "t_comprobante_cuarta", schema = "mig")
public class TComprobanteCuarta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdComprobante;
	private String chrCodComprobante;
	private String chrNomComprobante;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TRetenciones> TRetencioneses = new HashSet<TRetenciones>(0);

	public TComprobanteCuarta() {
	}

	public TComprobanteCuarta(int srlIdComprobante) {
		this.srlIdComprobante = srlIdComprobante;
	}

	public TComprobanteCuarta(int srlIdComprobante, String chrCodComprobante, String chrNomComprobante,
			String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica, Set<TRetenciones> TRetencioneses) {
		this.srlIdComprobante = srlIdComprobante;
		this.chrCodComprobante = chrCodComprobante;
		this.chrNomComprobante = chrNomComprobante;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TRetencioneses = TRetencioneses;
	}

	@Id
	@SequenceGenerator(name = "seq_comprobante_cuarta", sequenceName = "mig.t_comprobante_cuarta_srl_id_comprobante_seq")
	@GeneratedValue(generator = "seq_comprobante_cuarta")
	@Column(name = "srl_id_comprobante", unique = true, nullable = false)
	public int getSrlIdComprobante() {
		return this.srlIdComprobante;
	}

	public void setSrlIdComprobante(int srlIdComprobante) {
		this.srlIdComprobante = srlIdComprobante;
	}

	@Column(name = "chr_cod_comprobante", length = 1)
	public String getChrCodComprobante() {
		return this.chrCodComprobante;
	}

	public void setChrCodComprobante(String chrCodComprobante) {
		this.chrCodComprobante = chrCodComprobante;
	}

	@Column(name = "chr_nom_comprobante", length = 20)
	public String getChrNomComprobante() {
		return this.chrNomComprobante;
	}

	public void setChrNomComprobante(String chrNomComprobante) {
		this.chrNomComprobante = chrNomComprobante;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TComprobanteCuarta")
	public Set<TRetenciones> getTRetencioneses() {
		return this.TRetencioneses;
	}

	public void setTRetencioneses(Set<TRetenciones> TRetencioneses) {
		this.TRetencioneses = TRetencioneses;
	}

}
