package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TConvenioCuarta generated by hbm2java
 */
@Entity
@Table(name = "t_convenio_cuarta", schema = "mig")
public class TConvenioCuarta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdConvenio;
	private String chrCodConvenio;
	private String chrNomConvenio;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TPersonalCuarta> TPersonalCuartas = new HashSet<TPersonalCuarta>(0);

	public TConvenioCuarta() {
		super();
	}

	public TConvenioCuarta(int srlIdConvenio) {
		super();
		this.srlIdConvenio = srlIdConvenio;
	}

	public TConvenioCuarta(int srlIdConvenio, String chrCodConvenio, String chrNomConvenio, String chrFlgActivo,
			String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TPersonalCuarta> TPersonalCuartas) {
		this.srlIdConvenio = srlIdConvenio;
		this.chrCodConvenio = chrCodConvenio;
		this.chrNomConvenio = chrNomConvenio;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TPersonalCuartas = TPersonalCuartas;
	}

	@Id
	@SequenceGenerator(name = "seq_convenio_cuarta", sequenceName = "mig.t_convenio_cuarta_srl_id_convenio_seq")
	@GeneratedValue(generator = "seq_convenio_cuarta")
	@Column(name = "srl_id_convenio", unique = true, nullable = false)
	public int getSrlIdConvenio() {
		return this.srlIdConvenio;
	}

	public void setSrlIdConvenio(int srlIdConvenio) {
		this.srlIdConvenio = srlIdConvenio;
	}

	@Column(name = "chr_cod_convenio", length = 1)
	public String getChrCodConvenio() {
		return this.chrCodConvenio;
	}

	public void setChrCodConvenio(String chrCodConvenio) {
		this.chrCodConvenio = chrCodConvenio;
	}

	@Column(name = "chr_nom_convenio", length = 15)
	public String getChrNomConvenio() {
		return this.chrNomConvenio;
	}

	public void setChrNomConvenio(String chrNomConvenio) {
		this.chrNomConvenio = chrNomConvenio;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TConvenioCuarta")
	public Set<TPersonalCuarta> getTPersonalCuartas() {
		return this.TPersonalCuartas;
	}

	public void setTPersonalCuartas(Set<TPersonalCuarta> TPersonalCuartas) {
		this.TPersonalCuartas = TPersonalCuartas;
	}

}
