package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TFteFto generated by hbm2java
 */
@Entity
@Table(name = "t_cta_cte", schema = "mig")
public class TCtaCte implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdCta;
	private int srlIdFte;
	private String chrCodCta;
	private String chrNomCta;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TCtaCte() {
	}

	public TCtaCte(int srlIdCta) {
		this.srlIdCta = srlIdCta;
	}

	public TCtaCte(int srlIdCta, int srlIdFte, String chrCodCta, String chrNomCta, String chrFlgActivo, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdCta = srlIdCta;
		this.srlIdFte = srlIdFte;
		this.chrCodCta = chrCodCta;
		this.chrNomCta = chrNomCta;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	//@SequenceGenerator(name = "seq_cta_cte", sequenceName = "mig.t_cta_cte_srl_id_ctacte_seq")
	//@GeneratedValue(generator = "seq_cta_cte")
	@Column(name = "srl_id_ctacte", unique = true, nullable = false)
	public int getSrlIdCta() {
		return this.srlIdCta;
	}

	public void setSrlIdCta(int srlIdCta) {
		this.srlIdCta = srlIdCta;
	}

	@Column(name = "srl_id_fte")
	public int getSrlIdFte() {
		return this.srlIdFte;
	}

	public void setSrlIdFte(int srlIdFte) {
		this.srlIdFte = srlIdFte;
	}
	
	
	@Column(name = "chr_cod_ctacte", length = 2)
	public String getChrCodCta() {
		return this.chrCodCta;
	}

	public void setChrCodCta(String chrCodCta) {
		this.chrCodCta = chrCodCta;
	}

	@Column(name = "chr_nom_ctacte", length = 20)
	public String getChrNomCta() {
		return this.chrNomCta;
	}

	public void setChrNomCta(String chrNomCta) {
		this.chrNomCta = chrNomCta;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
