package pe.com.mig.model.entity;
// Generated 12/08/2016 12:06:48 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDetalleVoucher generated by hbm2java
 */
@Entity
@Table(name = "t_detalle_voucher", schema = "mig")
public class TDetalleVoucher implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdVoucher;
	private TComprasIngresos TComprasIngresos;
	private String chrNumVoucher;
	private Date dteFecVoucher;
	private BigDecimal numImpVoucher;
	private String imgVoucher;
	private Integer intIdfRegistro;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TDetalleVoucher() {
	}

	public TDetalleVoucher(int srlIdVoucher) {
		this.srlIdVoucher = srlIdVoucher;
	}

	public TDetalleVoucher(int srlIdVoucher, String chrNumVoucher, Date dteFecVoucher,
			BigDecimal numImpVoucher, String imgVoucher, Integer intIdfRegistro, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdVoucher = srlIdVoucher;
		this.chrNumVoucher = chrNumVoucher;
		this.dteFecVoucher = dteFecVoucher;
		this.numImpVoucher = numImpVoucher;
		this.imgVoucher = imgVoucher;
		this.intIdfRegistro = intIdfRegistro;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_detalle_voucher", sequenceName = "mig.t_detalle_voucher_srl_id_voucher_seq")
	@GeneratedValue(generator = "seq_detalle_voucher")
	@Column(name = "srl_id_voucher", unique = true, nullable = false)
	public int getSrlIdVoucher() {
		return this.srlIdVoucher;
	}

	public void setSrlIdVoucher(int srlIdVoucher) {
		this.srlIdVoucher = srlIdVoucher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_compras", nullable = false)
	public TComprasIngresos getTComprasIngresos() {
		return this.TComprasIngresos;
	}

	public void setTComprasIngresos(TComprasIngresos TComprasIngresos) {
		this.TComprasIngresos = TComprasIngresos;
	}

	@Column(name = "chr_num_voucher", length = 20)
	public String getChrNumVoucher() {
		return this.chrNumVoucher;
	}

	public void setChrNumVoucher(String chrNumVoucher) {
		this.chrNumVoucher = chrNumVoucher;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_voucher", length = 13)
	public Date getDteFecVoucher() {
		return this.dteFecVoucher;
	}

	public void setDteFecVoucher(Date dteFecVoucher) {
		this.dteFecVoucher = dteFecVoucher;
	}

	@Column(name = "num_imp_voucher", precision = 10)
	public BigDecimal getNumImpVoucher() {
		return this.numImpVoucher;
	}

	public void setNumImpVoucher(BigDecimal numImpVoucher) {
		this.numImpVoucher = numImpVoucher;
	}

	@Column(name = "img_voucher", length = 80)
	public String getImgVoucher() {
		return this.imgVoucher;
	}

	public void setImgVoucher(String imgVoucher) {
		this.imgVoucher = imgVoucher;
	}

	@Column(name = "int_idf_registro")
	public Integer getIntIdfRegistro() {
		return this.intIdfRegistro;
	}

	public void setIntIdfRegistro(Integer intIdfRegistro) {
		this.intIdfRegistro = intIdfRegistro;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
