package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDetalleBoleto generated by hbm2java
 */
@Entity
@Table(name = "t_detalle_boleto", schema = "mig")
public class TDetalleBoleto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdDboleto;
	private TRequeBoletos TRequeBoletos;
	private TTariBoleto TTariBoleto;
	private Integer numCntBoleto;
	private Integer numInicio;
	private Integer numFinal;
	private Integer intIdfRegistro;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TDetalleBoleto() {
	}
	
	public TDetalleBoleto(int srlIdDboleto) {
		this.srlIdDboleto = srlIdDboleto;
	}

	public TDetalleBoleto(int srlIdDboleto, TRequeBoletos TRequeBoletos, TTariBoleto TTariBoleto) {
		this.srlIdDboleto = srlIdDboleto;
		this.TRequeBoletos = TRequeBoletos;
		this.TTariBoleto = TTariBoleto;
	}

	public TDetalleBoleto(int srlIdDboleto, TRequeBoletos TRequeBoletos, TTariBoleto TTariBoleto, Integer numCntBoleto,
			Integer numInicio, Integer numFinal, String chrCodUsuaCreacion, Date dteFecCreacion,
			String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdDboleto = srlIdDboleto;
		this.TRequeBoletos = TRequeBoletos;
		this.TTariBoleto = TTariBoleto;
		this.numCntBoleto = numCntBoleto;
		this.numInicio = numInicio;
		this.numFinal = numFinal;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_detalle_boleto", sequenceName = "mig.t_detalle_boleto_srl_id_dboleto_seq")
	@GeneratedValue(generator = "seq_detalle_boleto")
	@Column(name = "srl_id_dboleto", unique = true, nullable = false)
	public int getSrlIdDboleto() {
		return this.srlIdDboleto;
	}

	public void setSrlIdDboleto(int srlIdDboleto) {
		this.srlIdDboleto = srlIdDboleto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_rboleto", nullable = false)
	public TRequeBoletos getTRequeBoletos() {
		return this.TRequeBoletos;
	}

	public void setTRequeBoletos(TRequeBoletos TRequeBoletos) {
		this.TRequeBoletos = TRequeBoletos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_boleto", nullable = false)
	public TTariBoleto getTTariBoleto() {
		return this.TTariBoleto;
	}

	public void setTTariBoleto(TTariBoleto TTariBoleto) {
		this.TTariBoleto = TTariBoleto;
	}

	@Column(name = "num_cnt_boleto")
	public Integer getNumCntBoleto() {
		return this.numCntBoleto;
	}

	public void setNumCntBoleto(Integer numCntBoleto) {
		this.numCntBoleto = numCntBoleto;
	}

	@Column(name = "num_inicio")
	public Integer getNumInicio() {
		return this.numInicio;
	}

	public void setNumInicio(Integer numInicio) {
		this.numInicio = numInicio;
	}

	@Column(name = "num_final")
	public Integer getNumFinal() {
		return this.numFinal;
	}

	public void setNumFinal(Integer numFinal) {
		this.numFinal = numFinal;
	}
	
	@Column(name = "int_idf_registro")
	public Integer getIntIdfRegistro() {
		return this.intIdfRegistro;
	}

	public void setIntIdfRegistro(Integer intIdfRegistro) {
		this.intIdfRegistro = intIdfRegistro;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
