package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.com.mig.model.entity.sppi.TEspecifica;

/**
 * TDetalleCompras generated by hbm2java
 */
@Entity
@Table(name = "t_detalle_compras", schema = "mig")
public class TDetalleCompras implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdDetalle;
	private TComprasIngresos TComprasIngresos;
	private TCuentaContable TCuentaContable;
	private TEspecifica TEspecifica;
	private String chrTipVenta;
	private BigDecimal numCntServicio;
	private BigDecimal numImpAfecto;
	private BigDecimal numImpNoafecto;
	private BigDecimal numImpIgv;
	private BigDecimal numImpIsc;
	private Integer intIdfRegistro;
	private String chrIndRetencion;
	private String chrNumRetencion;
	private Date dteFecPago;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private String chrCodMeta;

	public TDetalleCompras() {
	}

	public TDetalleCompras(int srlIdDetalle) {
		this.srlIdDetalle = srlIdDetalle;
	}

	public TDetalleCompras(int srlIdDetalle, TComprasIngresos TComprasIngresos, String chrCodUsuaCreacion,
			Date dteFecCreacion) {
		this.srlIdDetalle = srlIdDetalle;
		this.TComprasIngresos = TComprasIngresos;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
	}

	public TDetalleCompras(int srlIdDetalle, TComprasIngresos TComprasIngresos, BigDecimal numCntServicio,
			String chrTipVenta, BigDecimal numImpAfecto, BigDecimal numImpNoafecto, BigDecimal numImpIgv,
			BigDecimal numImpIsc, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica) {
		this.srlIdDetalle = srlIdDetalle;
		this.TComprasIngresos = TComprasIngresos;
		this.numCntServicio = numCntServicio;
		this.chrTipVenta = chrTipVenta;
		this.numImpAfecto = numImpAfecto;
		this.numImpNoafecto = numImpNoafecto;
		this.numImpIgv = numImpIgv;
		this.numImpIsc = numImpIsc;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_detalle_compras", sequenceName = "mig.t_detalle_compras_srl_id_detalle_seq")
	@GeneratedValue(generator = "seq_detalle_compras")
	@Column(name = "srl_id_detalle", unique = true, nullable = false)
	public int getSrlIdDetalle() {
		return this.srlIdDetalle;
	}

	public void setSrlIdDetalle(int srlIdDetalle) {
		this.srlIdDetalle = srlIdDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_compras", nullable = false)
	public TComprasIngresos getTComprasIngresos() {
		return this.TComprasIngresos;
	}

	public void setTComprasIngresos(TComprasIngresos TComprasIngresos) {
		this.TComprasIngresos = TComprasIngresos;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="srl_id_cuenta")
    public TCuentaContable getTCuentaContable() {
        return this.TCuentaContable;
    }
    
    public void setTCuentaContable(TCuentaContable TCuentaContable) {
        this.TCuentaContable = TCuentaContable;
    }

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_esp")
	public TEspecifica getTEspecifica() {
		return this.TEspecifica;
	}

	public void setTEspecifica(TEspecifica TEspecifica) {
		this.TEspecifica = TEspecifica;
	}

	@Column(name = "chr_tip_venta", length = 1)
	public String getChrTipVenta() {
		return this.chrTipVenta;
	}

	public void setChrTipVenta(String chrTipVenta) {
		this.chrTipVenta = chrTipVenta;
	}

	@Column(name = "num_cnt_servicio", precision = 10)
	public BigDecimal getNumCntServicio() {
		return this.numCntServicio;
	}

	public void setNumCntServicio(BigDecimal numCntServicio) {
		this.numCntServicio = numCntServicio;
	}

	@Column(name = "num_imp_afecto", precision = 10)
	public BigDecimal getNumImpAfecto() {
		return this.numImpAfecto;
	}

	public void setNumImpAfecto(BigDecimal numImpAfecto) {
		this.numImpAfecto = numImpAfecto;
	}

	@Column(name = "num_imp_noafecto", precision = 10)
	public BigDecimal getNumImpNoafecto() {
		return this.numImpNoafecto;
	}

	public void setNumImpNoafecto(BigDecimal numImpNoafecto) {
		this.numImpNoafecto = numImpNoafecto;
	}

	@Column(name = "num_imp_igv", precision = 10)
	public BigDecimal getNumImpIgv() {
		return this.numImpIgv;
	}

	public void setNumImpIgv(BigDecimal numImpIgv) {
		this.numImpIgv = numImpIgv;
	}

	@Column(name = "num_imp_isc", precision = 10)
	public BigDecimal getNumImpIsc() {
		return this.numImpIsc;
	}

	public void setNumImpIsc(BigDecimal numImpIsc) {
		this.numImpIsc = numImpIsc;
	}

	@Column(name = "int_idf_registro")
	public Integer getIntIdfRegistro() {
		return this.intIdfRegistro;
	}

	public void setIntIdfRegistro(Integer intIdfRegistro) {
		this.intIdfRegistro = intIdfRegistro;
	}
	
	@Column(name = "chr_ind_retencion", precision = 1)
	public String getChrIndRetencion() {
		return this.chrIndRetencion;
	}

	public void setChrIndRetencion(String chrIndRetencion) {
		this.chrIndRetencion = chrIndRetencion;
	}

	@Column(name = "chr_num_retencion", precision = 10)
	public String getChrNumRetencion() {
		return this.chrNumRetencion;
	}

	public void setChrNumRetencion(String chrNumRetencion) {
		this.chrNumRetencion = chrNumRetencion;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_pago", length = 13)
	public Date getDteFecPago() {
		return this.dteFecPago;
	}

	public void setDteFecPago(Date dteFecPago) {
		this.dteFecPago = dteFecPago;
	}

	@Column(name = "chr_cod_usua_creacion", nullable = false, length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", nullable = false, length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	/**
	 * @return the chrCodMeta
	 */
	@Column(name = "chr_cod_meta", precision = 5)
	public String getChrCodMeta() {
		return chrCodMeta;
	}

	/**
	 * @param chrCodMeta the chrCodMeta to set
	 */
	public void setChrCodMeta(String chrCodMeta) {
		this.chrCodMeta = chrCodMeta;
	}
}
