package pe.com.mig.model.entity;
// Generated 25/06/2016 11:26:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDireccionFactura generated by hbm2java
 */
@Entity
@Table(name = "t_direcc_fact", schema = "mig")
public class TDireccionFactura implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdDirec;
	private String chrCodDirec;
	private String chrTipOficina;
	private String chrNomAnp;
	private String chrNomUbigeo;
	private String chrDirec;
	private String chrRefDirec;
	private String chrLegal;
	private Set<TComprasIngresos> TComprasIngresoses = new HashSet<TComprasIngresos>(0);

	public TDireccionFactura() {
	}

	public TDireccionFactura(int srlIdDirec) {
		this.srlIdDirec = srlIdDirec;
	}

	public TDireccionFactura(int srlIdDirec, String chrCodDirec, String chrTipOficina, String chrNomAnp,
			String chrNomUbigeo, String chrDirec, String chrRefDirec,String chrLegal,
			Set<TComprasIngresos> TComprasIngresoses) {
		this.srlIdDirec = srlIdDirec;
		this.chrCodDirec = chrCodDirec;
		this.chrTipOficina = chrTipOficina;
		this.chrNomAnp = chrNomAnp;
		this.chrNomUbigeo = chrNomUbigeo;
		this.chrDirec = chrDirec;
		this.chrRefDirec = chrRefDirec;
		this.chrLegal = chrLegal;
		this.TComprasIngresoses = TComprasIngresoses;
	}

	@Id
	@SequenceGenerator(name = "seq_direc_factura", sequenceName = "mig.t_direcc_fact_srl_direcc_seq")
	@GeneratedValue(generator = "seq_direc_factura")
	@Column(name = "srl_direcc", unique = true, nullable = false)
	public int getSrlIdDirec() {
		return this.srlIdDirec;
	}

	public void setSrlIdDirec(int srlIdDirec) {
		this.srlIdDirec = srlIdDirec;
	}

	@Column(name = "chr_cod_direc")
	public String getChrCodDirec() {
		return this.chrCodDirec;
	}

	public void setChrCodDirec(String chrCodDirec) {
		this.chrCodDirec = chrCodDirec;
	}

	@Column(name = "chr_tip_direc")
	public String getChrTipOficina() {
		return this.chrTipOficina;
	}

	public void setChrTipOficina(String chrTipOficina) {
		this.chrTipOficina = chrTipOficina;
	}

	@Column(name = "chr_anp")
	public String getChrNomAnp() {
		return this.chrNomAnp;
	}

	public void setChrNomAnp(String chrNomAnp) {
		this.chrNomAnp = chrNomAnp;
	}
	@Column(name = "chr_ubigeo")
	public String getChrNomUbigeo() {
		return this.chrNomUbigeo;
	}

	public void setChrNomUbigeo(String chrNomUbigeo) {
		this.chrNomUbigeo = chrNomUbigeo;
	}
	@Column(name = "chr_direccion")
	public String getChrDirec() {
		return this.chrDirec;
	}

	public void setChrDirec(String chrDirec) {
		this.chrDirec = chrDirec;
	}
	@Column(name = "chr_ref")
	public String getChrRefDirec() {
		return this.chrRefDirec;
	}

	public void setChrRefDirec(String chrLegal) {
		this.chrRefDirec = chrRefDirec;
	}	
	@Column(name = "chr_legal")
	public String getChrLegal() {
		return this.chrLegal;
	}

	public void setChrLegal(String chrLegal) {
		this.chrLegal = chrLegal;
	}
}
