package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDocumentoIdentidad generated by hbm2java
 */
@Entity
@Table(name = "t_documento_identidad", schema = "mig")
public class TDocumentoIdentidad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdDocumento;
	private String chrCodDocumento;
	private String chrNomDocumento;
	private String chrDocSiglas;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TContratos> TContratoses = new HashSet<TContratos>(0);
	private Set<TTipoProveedor> TTipoProveedors = new HashSet<TTipoProveedor>(0);

	public TDocumentoIdentidad() {
	}

	public TDocumentoIdentidad(int srlIdDocumento) {
		this.srlIdDocumento = srlIdDocumento;
	}

	public TDocumentoIdentidad(int srlIdDocumento, String chrCodDocumento, String chrNomDocumento,
			String chrDocSiglas, String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion,
			String chrCodUsuaModifica, Date dteFecModifica, Set<TContratos> TContratoses,
			Set<TTipoProveedor> TTipoProveedors) {
		this.srlIdDocumento = srlIdDocumento;
		this.chrCodDocumento = chrCodDocumento;
		this.chrNomDocumento = chrNomDocumento;
		this.chrDocSiglas = chrDocSiglas;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TContratoses = TContratoses;
		this.TTipoProveedors = TTipoProveedors;
	}

	@Id
	@SequenceGenerator(name = "seq_documento_identidad", sequenceName = "mig.t_documento_identidad_srl_id_documento_seq")
	@GeneratedValue(generator = "seq_documento_identidad")
	@Column(name = "srl_id_documento", unique = true, nullable = false)
	public int getSrlIdDocumento() {
		return this.srlIdDocumento;
	}

	public void setSrlIdDocumento(int srlIdDocumento) {
		this.srlIdDocumento = srlIdDocumento;
	}

	@Column(name = "chr_cod_documento", length = 1)
	public String getChrCodDocumento() {
		return this.chrCodDocumento;
	}

	public void setChrCodDocumento(String chrCodDocumento) {
		this.chrCodDocumento = chrCodDocumento;
	}

	@Column(name = "chr_nom_documento", length = 50)
	public String getChrNomDocumento() {
		return this.chrNomDocumento;
	}

	public void setChrNomDocumento(String chrNomDocumento) {
		this.chrNomDocumento = chrNomDocumento;
	}

	@Column(name = "chr_doc_siglas", length = 5)
	public String getChrDocSiglas() {
		return this.chrDocSiglas;
	}

	public void setChrDocSiglas(String chrDocSiglas) {
		this.chrDocSiglas = chrDocSiglas;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDocumentoIdentidad")
	public Set<TContratos> getTContratoses() {
		return this.TContratoses;
	}

	public void setTContratoses(Set<TContratos> TContratoses) {
		this.TContratoses = TContratoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDocumentoIdentidad")
	public Set<TTipoProveedor> getTTipoProveedors() {
		return this.TTipoProveedors;
	}

	public void setTTipoProveedors(Set<TTipoProveedor> TTipoProveedors) {
		this.TTipoProveedors = TTipoProveedors;
	}

}
