package pe.com.mig.model.entity;
// Generated 25/06/2016 11:26:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEntregaBoleto generated by hbm2java
 */
@Entity
@Table(name = "t_entrega_boleto", schema = "mig")
public class TEntregaBoleto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdSalida;
	private TDetalleBoleto TDetalleBoleto;
	private String chrNumActa;
	private Date dteFecActa;
	private Integer numCntBoleto;
	private Integer numInicio;
	private Integer numFinal;
	private Integer intIdfRegistro;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TEntregaBoleto() {
	}
	
	public TEntregaBoleto(int srlIdSalida) {
		this.srlIdSalida = srlIdSalida;
	}

	public TEntregaBoleto(int srlIdSalida, TDetalleBoleto TDetalleBoleto) {
		this.srlIdSalida = srlIdSalida;
		this.TDetalleBoleto = TDetalleBoleto;
	}

	public TEntregaBoleto(int srlIdSalida, TDetalleBoleto TDetalleBoleto, String chrNumActa, Date dteFecActa,
			Integer numCntBoleto, Integer numInicio, Integer numFinal, Integer intIdfRegistro,
			String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdSalida = srlIdSalida;
		this.TDetalleBoleto = TDetalleBoleto;
		this.chrNumActa = chrNumActa;
		this.dteFecActa = dteFecActa;
		this.numCntBoleto = numCntBoleto;
		this.numInicio = numInicio;
		this.numFinal = numFinal;
		this.intIdfRegistro = intIdfRegistro;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_entrega_boleto", sequenceName = "mig.t_entrega_boleto_srl_id_salida_seq")
	@GeneratedValue(generator = "seq_entrega_boleto")
	@Column(name = "srl_id_salida", unique = true, nullable = false)
	public int getSrlIdSalida() {
		return this.srlIdSalida;
	}

	public void setSrlIdSalida(int srlIdSalida) {
		this.srlIdSalida = srlIdSalida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_dboleto", nullable = false)
	public TDetalleBoleto getTDetalleBoleto() {
		return this.TDetalleBoleto;
	}

	public void setTDetalleBoleto(TDetalleBoleto TDetalleBoleto) {
		this.TDetalleBoleto = TDetalleBoleto;
	}

	@Column(name = "chr_num_acta", length = 7)
	public String getChrNumActa() {
		return this.chrNumActa;
	}

	public void setChrNumActa(String chrNumActa) {
		this.chrNumActa = chrNumActa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_acta", length = 13)
	public Date getDteFecActa() {
		return this.dteFecActa;
	}

	public void setDteFecActa(Date dteFecActa) {
		this.dteFecActa = dteFecActa;
	}

	@Column(name = "num_cnt_boleto")
	public Integer getNumCntBoleto() {
		return this.numCntBoleto;
	}

	public void setNumCntBoleto(Integer numCntBoleto) {
		this.numCntBoleto = numCntBoleto;
	}

	@Column(name = "num_inicio")
	public Integer getNumInicio() {
		return this.numInicio;
	}

	public void setNumInicio(Integer numInicio) {
		this.numInicio = numInicio;
	}

	@Column(name = "num_final")
	public Integer getNumFinal() {
		return this.numFinal;
	}

	public void setNumFinal(Integer numFinal) {
		this.numFinal = numFinal;
	}

	@Column(name = "int_idf_registro")
	public Integer getIntIdfRegistro() {
		return this.intIdfRegistro;
	}

	public void setIntIdfRegistro(Integer intIdfRegistro) {
		this.intIdfRegistro = intIdfRegistro;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
