package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEntidadFinanciera generated by hbm2java
 */
@Entity
@Table(name = "t_entidad_financiera", schema = "mig")
public class TEntidadFinanciera implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdEntidad;
	private String chrCodEntidad;
	private String chrNomEntidad;
	private Long numRuc;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TCartaFianza> TCartaFianzas = new HashSet<TCartaFianza>(0);

	public TEntidadFinanciera() {
	}

	public TEntidadFinanciera(int srlIdEntidad) {
		this.srlIdEntidad = srlIdEntidad;
	}

	public TEntidadFinanciera(int srlIdEntidad, String chrCodEntidad, String chrNomEntidad, Long numRuc,
			String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica, Set<TCartaFianza> TCartaFianzas) {
		this.srlIdEntidad = srlIdEntidad;
		this.chrCodEntidad = chrCodEntidad;
		this.chrNomEntidad = chrNomEntidad;
		this.numRuc = numRuc;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TCartaFianzas = TCartaFianzas;
	}

	@Id
	@SequenceGenerator(name = "seq_entidad_financiera", sequenceName = "mig.t_entidad_financiera_srl_id_entidad_seq")
	@GeneratedValue(generator = "seq_entidad_financiera")
	@Column(name = "srl_id_entidad", unique = true, nullable = false)
	public int getSrlIdEntidad() {
		return this.srlIdEntidad;
	}

	public void setSrlIdEntidad(int srlIdEntidad) {
		this.srlIdEntidad = srlIdEntidad;
	}

	@Column(name = "chr_cod_entidad", length = 2)
	public String getChrCodEntidad() {
		return this.chrCodEntidad;
	}

	public void setChrCodEntidad(String chrCodEntidad) {
		this.chrCodEntidad = chrCodEntidad;
	}

	@Column(name = "chr_nom_entidad", length = 30)
	public String getChrNomEntidad() {
		return this.chrNomEntidad;
	}

	public void setChrNomEntidad(String chrNomEntidad) {
		this.chrNomEntidad = chrNomEntidad;
	}

	@Column(name = "num_ruc")
	public Long getNumRuc() {
		return this.numRuc;
	}

	public void setNumRuc(Long numRuc) {
		this.numRuc = numRuc;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TEntidadFinanciera")
	public Set<TCartaFianza> getTCartaFianzas() {
		return this.TCartaFianzas;
	}

	public void setTCartaFianzas(Set<TCartaFianza> TCartaFianzas) {
		this.TCartaFianzas = TCartaFianzas;
	}

}
