package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TFteFto generated by hbm2java
 */
@Entity
@Table(name = "t_fte_fto", schema = "mig")
public class TFteFto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdFte;
	private String chrCodFte;
	private String chrNomFte;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TFteFto() {
	}

	public TFteFto(int srlIdFte) {
		this.srlIdFte = srlIdFte;
	}

	public TFteFto(int srlIdFte, String chrCodFte, String chrNomFte, String chrFlgActivo, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdFte = srlIdFte;
		this.chrCodFte = chrCodFte;
		this.chrNomFte = chrNomFte;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_fte_fto", sequenceName = "mig.t_fte_fto_srl_id_fte_seq")
	@GeneratedValue(generator = "seq_fte_fto")
	@Column(name = "srl_id_fte", unique = true, nullable = false)
	public int getSrlIdFte() {
		return this.srlIdFte;
	}

	public void setSrlIdFte(int srlIdFte) {
		this.srlIdFte = srlIdFte;
	}

	@Column(name = "chr_cod_fte", length = 2)
	public String getChrCodFte() {
		return this.chrCodFte;
	}

	public void setChrCodFte(String chrCodFte) {
		this.chrCodFte = chrCodFte;
	}

	@Column(name = "chr_nom_fte", length = 50)
	public String getChrNomFte() {
		return this.chrNomFte;
	}

	public void setChrNomFte(String chrNomFte) {
		this.chrNomFte = chrNomFte;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
