package pe.com.mig.model.entity;
// Generated 25/06/2016 11:26:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMedioPago generated by hbm2java
 */
@Entity
@Table(name = "t_medio_pago", schema = "mig")
public class TMedioPago implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdMedio;
	private String chrCodMedio;
	private String chrNomMedio;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TComprasIngresos> TComprasIngresoses = new HashSet<TComprasIngresos>(0);

	public TMedioPago() {
	}

	public TMedioPago(int srlIdMedio) {
		this.srlIdMedio = srlIdMedio;
	}

	public TMedioPago(int srlIdMedio, String chrCodMedio, String chrNomMedio, String chrFlgActivo,
			String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TComprasIngresos> TComprasIngresoses) {
		this.srlIdMedio = srlIdMedio;
		this.chrCodMedio = chrCodMedio;
		this.chrNomMedio = chrNomMedio;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TComprasIngresoses = TComprasIngresoses;
	}

	@Id
	@SequenceGenerator(name = "seq_medio_pago", sequenceName = "mig.t_medio_pago_srl_id_medio_seq")
	@GeneratedValue(generator = "seq_medio_pago")
	@Column(name = "srl_id_medio", unique = true, nullable = false)
	public int getSrlIdMedio() {
		return this.srlIdMedio;
	}

	public void setSrlIdMedio(int srlIdMedio) {
		this.srlIdMedio = srlIdMedio;
	}

	@Column(name = "chr_cod_medio", length = 3)
	public String getChrCodMedio() {
		return this.chrCodMedio;
	}

	public void setChrCodMedio(String chrCodMedio) {
		this.chrCodMedio = chrCodMedio;
	}

	@Column(name = "chr_nom_medio", length = 200)
	public String getChrNomMedio() {
		return this.chrNomMedio;
	}

	public void setChrNomMedio(String chrNomMedio) {
		this.chrNomMedio = chrNomMedio;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMedioPago")
	public Set<TComprasIngresos> getTComprasIngresoses() {
		return this.TComprasIngresoses;
	}

	public void setTComprasIngresoses(Set<TComprasIngresos> TComprasIngresoses) {
		this.TComprasIngresoses = TComprasIngresoses;
	}

}
