package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TNacionalidad generated by hbm2java
 */
@Entity
@Table(name = "t_nacionalidad", schema = "mig")
public class TNacionalidad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdNacion;
	private String chrCodNacion;
	private String chrNomNacion;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TPersonalCuarta> TPersonalCuartas = new HashSet<TPersonalCuarta>(0);

	public TNacionalidad() {
		super();
	}

	public TNacionalidad(int srlIdNacion) {
		super();
		this.srlIdNacion = srlIdNacion;
	}

	public TNacionalidad(int srlIdNacion, String chrCodNacion, String chrNomNacion, String chrFlgActivo,
			String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TPersonalCuarta> TPersonalCuartas) {
		this.srlIdNacion = srlIdNacion;
		this.chrCodNacion = chrCodNacion;
		this.chrNomNacion = chrNomNacion;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TPersonalCuartas = TPersonalCuartas;
	}

	@Id
	@SequenceGenerator(name = "seq_nacionalidad", sequenceName = "mig.t_nacionalidad_srl_id_nacion_seq")
	@GeneratedValue(generator = "seq_nacionalidad")
	@Column(name = "srl_id_nacion", unique = true, nullable = false)
	public int getSrlIdNacion() {
		return this.srlIdNacion;
	}

	public void setSrlIdNacion(int srlIdNacion) {
		this.srlIdNacion = srlIdNacion;
	}

	@Column(name = "chr_cod_nacion", length = 6)
	public String getChrCodNacion() {
		return this.chrCodNacion;
	}

	public void setChrCodNacion(String chrCodNacion) {
		this.chrCodNacion = chrCodNacion;
	}

	@Column(name = "chr_nom_nacion", length = 50)
	public String getChrNomNacion() {
		return this.chrNomNacion;
	}

	public void setChrNomNacion(String chrNomNacion) {
		this.chrNomNacion = chrNomNacion;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNacionalidad")
	public Set<TPersonalCuarta> getTPersonalCuartas() {
		return this.TPersonalCuartas;
	}

	public void setTPersonalCuartas(Set<TPersonalCuarta> TPersonalCuartas) {
		this.TPersonalCuartas = TPersonalCuartas;
	}

}
