package pe.com.mig.model.entity;
// Generated 07/07/2016 11:39:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOtros generated by hbm2java
 */
@Entity
@Table(name = "t_otros", schema = "mig")
public class TOtros implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdOtros;
	private String chrNomOtros;
	private String chrFlgActivo;
	private String chrCodEspecifica;
	private String chrCodCuenta;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private String chrSiglas;
	private Set<TDetalleIngresos> TDetalleIngresoses = new HashSet<TDetalleIngresos>(0);

	public TOtros() {
	}

	public TOtros(int srlIdOtros) {
		this.srlIdOtros = srlIdOtros;
	}

	public TOtros(int srlIdOtros, String chrNomOtros, String chrFlgActivo, String chrCodEspecifica,
			String chrCodCuenta, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica, String chrSiglas, Set<TDetalleIngresos> TDetalleIngresoses) {
		this.srlIdOtros = srlIdOtros;
		this.chrNomOtros = chrNomOtros;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodEspecifica = chrCodEspecifica;
		this.chrCodCuenta = chrCodCuenta;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.chrSiglas = chrSiglas;
		this.TDetalleIngresoses = TDetalleIngresoses;
	}

	@Id
	@SequenceGenerator(name = "seq_otros", sequenceName = "mig.t_otros_srl_id_otros_seq")
	@GeneratedValue(generator = "seq_otros")
	@Column(name = "srl_id_otros", unique = true, nullable = false)
	public int getSrlIdOtros() {
		return this.srlIdOtros;
	}

	public void setSrlIdOtros(int srlIdOtros) {
		this.srlIdOtros = srlIdOtros;
	}

	@Column(name = "chr_nom_otros", length = 80)
	public String getChrNomOtros() {
		return this.chrNomOtros;
	}

	public void setChrNomOtros(String chrNomOtros) {
		this.chrNomOtros = chrNomOtros;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_especifica", length = 15)
	public String getChrCodEspecifica() {
		return this.chrCodEspecifica;
	}

	public void setChrCodEspecifica(String chrCodEspecifica) {
		this.chrCodEspecifica = chrCodEspecifica;
	}

	@Column(name = "chr_cod_cuenta", length = 15)
	public String getChrCodCuenta() {
		return this.chrCodCuenta;
	}

	public void setChrCodCuenta(String chrCodCuenta) {
		this.chrCodCuenta = chrCodCuenta;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOtros")
	public Set<TDetalleIngresos> getTDetalleIngresoses() {
		return this.TDetalleIngresoses;
	}

	public void setTDetalleIngresoses(Set<TDetalleIngresos> TDetalleIngresoses) {
		this.TDetalleIngresoses = TDetalleIngresoses;
	}

	/**
	 * @return the chrSiglas
	 */
	@Column(name = "chr_siglas", length = 5)
	public String getChrSiglas() {
		return chrSiglas;
	}

	/**
	 * @param chrSiglas the chrSiglas to set
	 */
	public void setChrSiglas(String chrSiglas) {
		this.chrSiglas = chrSiglas;
	}
}
