package pe.com.mig.model.entity;
// Generated 02/07/2016 12:36:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TProducto generated by hbm2java
 */
@Entity
@Table(name = "t_producto", schema = "mig")
public class TProducto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdProducto;
	private TUnidadMedida TUnidadMedida;
	private String chrCodProducto;
	private String chrNomProducto;
	private BigDecimal impPctUit;
	private BigDecimal numImpUnit;
	private BigDecimal numImpIgv;
	private BigDecimal numImpPventa;
	private BigDecimal numImpProducto;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private String chrCodEspecifica;
	private String chrCodCuenta;
	private String chrNomCuenta;
	private Set<TDetalleIngresos> TDetalleIngresoses = new HashSet<TDetalleIngresos>(0);

	public TProducto() {
	}

	public TProducto(int srlIdProducto) {
		this.srlIdProducto = srlIdProducto;
	}

	public TProducto(int srlIdProducto, TUnidadMedida TUnidadMedida, String chrCodProducto, String chrNomProducto,
			BigDecimal impPctUit, BigDecimal numImpUnit, BigDecimal numImpIgv, BigDecimal numImpPventa,
			BigDecimal numImpProducto, String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion,
			String chrCodUsuaModifica, Date dteFecModifica, Set<TDetalleIngresos> TDetalleIngresoses) {
		this.srlIdProducto = srlIdProducto;
		this.TUnidadMedida = TUnidadMedida;
		this.chrCodProducto = chrCodProducto;
		this.chrNomProducto = chrNomProducto;
		this.impPctUit = impPctUit;
		this.numImpUnit = numImpUnit;
		this.numImpIgv = numImpIgv;
		this.numImpPventa = numImpPventa;
		this.numImpProducto = numImpProducto;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TDetalleIngresoses = TDetalleIngresoses;
	}

	@Id
	@SequenceGenerator(name = "seq_producto", sequenceName = "mig.t_producto_srl_id_producto_seq")
	@GeneratedValue(generator = "seq_producto")
	@Column(name = "srl_id_producto", unique = true, nullable = false)
	public int getSrlIdProducto() {
		return this.srlIdProducto;
	}

	public void setSrlIdProducto(int srlIdProducto) {
		this.srlIdProducto = srlIdProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_unidad")
	public TUnidadMedida getTUnidadMedida() {
		return this.TUnidadMedida;
	}

	public void setTUnidadMedida(TUnidadMedida TUnidadMedida) {
		this.TUnidadMedida = TUnidadMedida;
	}

	@Column(name = "chr_cod_producto", length = 2)
	public String getChrCodProducto() {
		return this.chrCodProducto;
	}

	public void setChrCodProducto(String chrCodProducto) {
		this.chrCodProducto = chrCodProducto;
	}

	@Column(name = "chr_nom_producto", length = 50)
	public String getChrNomProducto() {
		return this.chrNomProducto;
	}

	public void setChrNomProducto(String chrNomProducto) {
		this.chrNomProducto = chrNomProducto;
	}

	@Column(name = "imp_pct_uit", precision = 10, scale = 4)
	public BigDecimal getImpPctUit() {
		return this.impPctUit;
	}

	public void setImpPctUit(BigDecimal impPctUit) {
		this.impPctUit = impPctUit;
	}

	@Column(name = "num_imp_unit", precision = 10)
	public BigDecimal getNumImpUnit() {
		return this.numImpUnit;
	}

	public void setNumImpUnit(BigDecimal numImpUnit) {
		this.numImpUnit = numImpUnit;
	}

	@Column(name = "num_imp_igv", precision = 10)
	public BigDecimal getNumImpIgv() {
		return this.numImpIgv;
	}

	public void setNumImpIgv(BigDecimal numImpIgv) {
		this.numImpIgv = numImpIgv;
	}

	@Column(name = "num_imp_pventa", precision = 10)
	public BigDecimal getNumImpPventa() {
		return this.numImpPventa;
	}

	public void setNumImpPventa(BigDecimal numImpPventa) {
		this.numImpPventa = numImpPventa;
	}

	@Column(name = "num_imp_producto", precision = 10)
	public BigDecimal getNumImpProducto() {
		return this.numImpProducto;
	}

	public void setNumImpProducto(BigDecimal numImpProducto) {
		this.numImpProducto = numImpProducto;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProducto")
	public Set<TDetalleIngresos> getTDetalleIngresoses() {
		return this.TDetalleIngresoses;
	}

	public void setTDetalleIngresoses(Set<TDetalleIngresos> TDetalleIngresoses) {
		this.TDetalleIngresoses = TDetalleIngresoses;
	}
	/**
	 * @return the chrCodEspecifica
	 */
	@Column(name = "chr_cod_especifica", length = 15)
	public String getChrCodEspecifica() {
		return chrCodEspecifica;
	}

	/**
	 * @param chrCodEspecifica the chrCodEspecifica to set
	 */
	public void setChrCodEspecifica(String chrCodEspecifica) {
		this.chrCodEspecifica = chrCodEspecifica;
	}

	/**
	 * @return the chrCodCuenta
	 */
	@Column(name = "chr_cod_cuenta", length = 15)
	public String getChrCodCuenta() {
		return chrCodCuenta;
	}

	/**
	 * @param chrCodCuenta the chrCodCuenta to set
	 */
	public void setChrCodCuenta(String chrCodCuenta) {
		this.chrCodCuenta = chrCodCuenta;
	}

	/**
	 * @return the chrNomCuenta
	 */
	@Column(name = "chr_nom_cuenta", length = 150)
	public String getChrNomCuenta() {
		return chrNomCuenta;
	}

	/**
	 * @param chrNomCuenta the chrNomCuenta to set
	 */
	public void setChrNomCuenta(String chrNomCuenta) {
		this.chrNomCuenta = chrNomCuenta;
	}

	
	
}
