package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.com.mig.model.entity.sde.TbtRegistroNac;
import pe.com.mig.model.entity.sernanp.Unidadoperativa;

/**
 * TRetenciones generated by hbm2java
 */
@Entity
@Table(name = "t_retenciones", schema = "mig")
public class TRetenciones implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdRetenciones;
	private TComprobanteCuarta TComprobanteCuarta;
	private TPersonalCuarta TPersonalCuarta;
	private Unidadoperativa unidadoperativa;
	private TbtRegistroNac tbtRegistroNac;
	private String chrNumSerie;
	private String chrNumComprobante;
	private Date dteFecDocumento;
	private String chrIndRetencion;
	private Date dteFecPago;
	private String chrNumRetencion;
	private BigDecimal intNumSubtotal;
	private BigDecimal intImpRetenido;
	private BigDecimal intImpTotal;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModificacion;
	private Date dteFecModifica;
	private Integer intIdfRegistro;
	private String chrTipOperacion;
	private Integer intCodPadComRecibo;
	

	public TRetenciones() {
	}

	public TRetenciones(int srlIdRetenciones, TComprobanteCuarta TComprobanteCuarta, TPersonalCuarta TPersonalCuarta) {
		this.srlIdRetenciones = srlIdRetenciones;
		this.TComprobanteCuarta = TComprobanteCuarta;
		this.TPersonalCuarta = TPersonalCuarta;
	}

	public TRetenciones(int srlIdRetenciones, TComprobanteCuarta TComprobanteCuarta, TPersonalCuarta TPersonalCuarta,
			String chrNumSerie, String chrNumComprobante, Date dteFecDocumento,
			String chrIndRetencion, Date dteFecPago, String chrNumRetencion, BigDecimal intNumSubtotal,
			BigDecimal intImpRetenido, BigDecimal intImpTotal, String chrCodUsuaCreacion, Date dteFecCreacion,
			String chrCodUsuaModificacion, Date dteFecModifica) {
		this.srlIdRetenciones = srlIdRetenciones;
		this.TComprobanteCuarta = TComprobanteCuarta;
		this.TPersonalCuarta = TPersonalCuarta;
		this.chrNumSerie = chrNumSerie;
		this.chrNumComprobante = chrNumComprobante;
		this.dteFecDocumento = dteFecDocumento;
		this.chrIndRetencion = chrIndRetencion;
		this.dteFecPago = dteFecPago;
		this.chrNumRetencion = chrNumRetencion;
		this.intNumSubtotal = intNumSubtotal;
		this.intImpRetenido = intImpRetenido;
		this.intImpTotal = intImpTotal;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModificacion = chrCodUsuaModificacion;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	@SequenceGenerator(name = "seq_retenciones", sequenceName = "mig.t_retenciones_srl_id_retenciones_seq")
	@GeneratedValue(generator = "seq_retenciones")
	@Column(name = "srl_id_retenciones", unique = true, nullable = false)
	public int getSrlIdRetenciones() {
		return this.srlIdRetenciones;
	}

	public void setSrlIdRetenciones(int srlIdRetenciones) {
		this.srlIdRetenciones = srlIdRetenciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_comprobante", nullable = false)
	public TComprobanteCuarta getTComprobanteCuarta() {
		return this.TComprobanteCuarta;
	}

	public void setTComprobanteCuarta(TComprobanteCuarta TComprobanteCuarta) {
		this.TComprobanteCuarta = TComprobanteCuarta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_personal", nullable = false)
	public TPersonalCuarta getTPersonalCuarta() {
		return this.TPersonalCuarta;
	}

	public void setTPersonalCuarta(TPersonalCuarta TPersonalCuarta) {
		this.TPersonalCuarta = TPersonalCuarta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idunidad")
	public Unidadoperativa getUnidadoperativa() {
		return this.unidadoperativa;
	}

	public void setUnidadoperativa(Unidadoperativa unidadoperativa) {
		this.unidadoperativa = unidadoperativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_adm")
	public TbtRegistroNac getTbtRegistroNac() {
		return this.tbtRegistroNac;
	}

	public void setTbtRegistroNac(TbtRegistroNac tbtRegistroNac) {
		this.tbtRegistroNac = tbtRegistroNac;
	}

	@Column(name = "chr_num_serie", length = 5)
	public String getChrNumSerie() {
		return this.chrNumSerie;
	}

	public void setChrNumSerie(String chrNumSerie) {
		this.chrNumSerie = chrNumSerie;
	}

	@Column(name = "chr_num_comprobante", length = 7)
	public String getChrNumComprobante() {
		return this.chrNumComprobante;
	}

	public void setChrNumComprobante(String chrNumComprobante) {
		this.chrNumComprobante = chrNumComprobante;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_documento", length = 13)
	public Date getDteFecDocumento() {
		return this.dteFecDocumento;
	}

	public void setDteFecDocumento(Date dteFecDocumento) {
		this.dteFecDocumento = dteFecDocumento;
	}

	@Column(name = "chr_ind_retencion", length = 1)
	public String getChrIndRetencion() {
		return this.chrIndRetencion;
	}

	public void setChrIndRetencion(String chrIndRetencion) {
		this.chrIndRetencion = chrIndRetencion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_pago", length = 13)
	public Date getDteFecPago() {
		return this.dteFecPago;
	}

	public void setDteFecPago(Date dteFecPago) {
		this.dteFecPago = dteFecPago;
	}

	@Column(name = "chr_num_retencion", length = 5)
	public String getChrNumRetencion() {
		return this.chrNumRetencion;
	}

	public void setChrNumRetencion(String chrNumRetencion) {
		this.chrNumRetencion = chrNumRetencion;
	}

	@Column(name = "int_num_subtotal", precision = 10)
	public BigDecimal getIntNumSubtotal() {
		return this.intNumSubtotal;
	}

	public void setIntNumSubtotal(BigDecimal intNumSubtotal) {
		this.intNumSubtotal = intNumSubtotal;
	}

	@Column(name = "int_imp_retenido", precision = 10)
	public BigDecimal getIntImpRetenido() {
		return this.intImpRetenido;
	}

	public void setIntImpRetenido(BigDecimal intImpRetenido) {
		this.intImpRetenido = intImpRetenido;
	}

	@Column(name = "int_imp_total", precision = 10)
	public BigDecimal getIntImpTotal() {
		return this.intImpTotal;
	}

	public void setIntImpTotal(BigDecimal intImpTotal) {
		this.intImpTotal = intImpTotal;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modificacion", length = 20)
	public String getChrCodUsuaModificacion() {
		return this.chrCodUsuaModificacion;
	}

	public void setChrCodUsuaModificacion(String chrCodUsuaModificacion) {
		this.chrCodUsuaModificacion = chrCodUsuaModificacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}
	
	@Column(name = "int_idf_registro")
	public Integer getIntIdfRegistro() {
		return this.intIdfRegistro;
	}

	public void setIntIdfRegistro(Integer intIdfRegistro) {
		this.intIdfRegistro = intIdfRegistro;
	}
	
	@Column(name = "chr_tip_operacion", length = 1)
	public String getChrTipOperacion() {
		return this.chrTipOperacion;
	}

	public void setChrTipOperacion(String chrTipOperacion) {
		this.chrTipOperacion = chrTipOperacion;
	}

	/**
	 * @return the intCodPadComRecibo
	 */
	@Column(name = "int_cod_pad_com_recibo" )
	public Integer getIntCodPadComRecibo() {
		return intCodPadComRecibo;
	}

	/**
	 * @param intCodPadComRecibo the intCodPadComRecibo to set
	 */
	public void setIntCodPadComRecibo(Integer intCodPadComRecibo) {
		this.intCodPadComRecibo = intCodPadComRecibo;
	}

 

}
