package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.com.mig.model.entity.sde.TbtRegistroNac;
import pe.com.mig.model.entity.sernanp.Unidadoperativa;

/**
 * TSeries generated by hbm2java
 */
@Entity
@Table(name = "t_serie_anp", schema = "mig")
public class TSeriesNum implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdSerie;
	private int intCodUnidad;
	private int intCodRanac;
	private int intCodCp;
	private String chrCodSunat;
	private String numSerie;
	private String intNumCp;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TSeriesNum() {
	}

	public TSeriesNum(int srlIdSerie) {
		this.srlIdSerie = srlIdSerie;
	}

	public TSeriesNum(int srlIdSerie, int intCodCp, String chrCodSunat,String numSerie, String intNumCp, 
				String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdSerie = srlIdSerie;
		this.intCodCp = intCodCp;
		this.chrCodSunat = chrCodSunat;
		this.numSerie = numSerie;
		this.intNumCp = intNumCp;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}


	@Id
	//@SequenceGenerator(name = "seq_anp_sucur", sequenceName = "mig.t_anp_sucur_srl_id_sucur_seq")
	//@GeneratedValue(generator = "seq_anp_sucur")
	@Column(name = "srl_id_serie", unique = true, nullable = false)
	public int getSrlIdSerie() {
		return this.srlIdSerie;
	}

	public void setSrlIdSerie(int srlIdSerie) {
		this.srlIdSerie = srlIdSerie;
	}

	@Column(name = "chr_cod_sunat")
	public String getChrCodSunat() {
		return this.chrCodSunat;
	}

	public void setChrCodSunat(String chrCodSunat) {
		this.chrCodSunat = chrCodSunat;
	}

	/**
	 * @return the numSerie
	 */
	@Column(name = "chr_cod_serie")
	public String getNumSerie() {
		return numSerie;
	}

	/**
	 * @param numSerie the numSerie to set
	 */
	public void setNumSerie(String numSerie) {
		this.numSerie = numSerie;
	}
	
	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}


	/**
	 * @return the intNumCp
	 */
	@Column(name = "int_num_cp")
	public String getIntNumCp() {
		return intNumCp;
	}

	/**
	 * @param intNumCp the intNumCp to set
	 */
	public void setIntNumCp(String intNumCp) {
		this.intNumCp = intNumCp;
	}

	/**
	 * @return the intCodUnidad
	 */
	@Column(name = "idunidad")
	public int getIntCodUnidad() {
		return intCodUnidad;
	}

	/**
	 * @param intCodUnidad the intCodUnidad to set
	 */
	public void setIntCodUnidad(int intCodUnidad) {
		this.intCodUnidad = intCodUnidad;
	}

	/**
	 * @return the intCodRanac
	 */
	@Column(name = "id_ranac")
	public int getIntCodRanac() {
		return intCodRanac;
	}

	/**
	 * @param intCodRanac the intCodRanac to set
	 */
	public void setIntCodRanac(int intCodRanac) {
		this.intCodRanac = intCodRanac;
	}

	/**
	 * @return the intCodCp
	 */
	@Column(name = "srl_id_comprobante")
	public int getIntCodCp() {
		return intCodCp;
	}

	/**
	 * @param intCodCp the intCodCp to set
	 */
	public void setIntCodCp(int intCodCp) {
		this.intCodCp = intCodCp;
	}



	
}
