package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSucursal generated by hbm2java
 */
@Entity
@Table(name = "t_anp_sucur", schema = "mig")
public class TSucursal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdSucur;
	private int intUnidad;
	private int intAnp;
	private String chrDesSuc;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;

	public TSucursal() {
	}

	public TSucursal(int srlIdSucur) {
		this.srlIdSucur = srlIdSucur;
	}

	public TSucursal(int srlIdSucur, int intUnidad,int intAnp, String chrDesSuc, String chrFlgActivo, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica) {
		this.srlIdSucur = srlIdSucur;
		this.intUnidad = intUnidad;
		this.intAnp = intAnp;
		this.chrDesSuc = chrDesSuc;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
	}

	@Id
	//@SequenceGenerator(name = "seq_anp_sucur", sequenceName = "mig.t_anp_sucur_srl_id_sucur_seq")
	//@GeneratedValue(generator = "seq_anp_sucur")
	@Column(name = "srl_id_sucur", unique = true, nullable = false)
	public int getSrlIdSucur() {
		return this.srlIdSucur;
	}

	public void setSrlIdSucur(int srlIdSucur) {
		this.srlIdSucur = srlIdSucur;
	}

	@Column(name = "idunidad")
	public int getIntUnidad() {
		return this.intUnidad;
	}

	public void setIntUnidad(int intUnidad) {
		this.intUnidad = intUnidad;
	}
	
	@Column(name = "id_ranac")
	public int getIntAnp() {
		return this.intAnp;
	}

	public void setIntAnp(int intAnp) {
		this.intAnp = intAnp;
	}
	
	@Column(name = "chr_nom_sucur", length = 40)
	public String getChrDesSuc() {
		return this.chrDesSuc;
	}

	public void setChrDesSuc(String chrDesSuc) {
		this.chrDesSuc = chrDesSuc;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

}
