package pe.com.mig.model.entity;
// Generated 02/07/2016 12:36:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pe.com.mig.model.entity.sde.TbtRegistroNac;
import pe.com.mig.model.entity.sernanp.Unidadoperativa;

/**
 * TTariBoleto generated by hbm2java
 */
@Entity
@Table(name = "t_tari_boleto", schema = "mig")
public class TTariBoleto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdBoleto;
	private Unidadoperativa unidadoperativa;
	private TbtRegistroNac tbtRegistroNac;
	private String chrNomBoleto;
	private String chrCodBoleto;
	private Integer intIdfTarifa;
	private BigDecimal numImpUnit;
	private String intNumSerie;
	private Integer numCntIngreso;
	private Integer numCntSalida;
	private Integer numCntStock;
	private Integer numInicio;
	private Integer numFinal;
	private String chrFlgActivo;
	private String chrCodPartida;
	private String chrCodCuenta;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private String chrNomCuenta;
	private Set<TDetalleIngresos> TDetalleIngresoses = new HashSet<TDetalleIngresos>(0);
	private Set<TDetalleBoleto> TDetalleBoletos = new HashSet<TDetalleBoleto>(0);

	public TTariBoleto() {
	}

	public TTariBoleto(int srlIdBoleto) {
		this.srlIdBoleto = srlIdBoleto;
	}

	public TTariBoleto(int srlIdBoleto, String chrNomBoleto, String chrCodBoleto,
			Integer intIdfTarifa, BigDecimal numImpUnit, String intNumSerie, Integer numCntIngreso,
			Integer numCntSalida, Integer numCntStock, String chrFlgActivo, String chrCodPartida,
			String chrCodCuenta, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica, Set<TDetalleIngresos> TDetalleIngresoses, Set<TDetalleBoleto> TDetalleBoletos) {
		this.srlIdBoleto = srlIdBoleto;
		this.chrNomBoleto = chrNomBoleto;
		this.chrCodBoleto = chrCodBoleto;
		this.intIdfTarifa = intIdfTarifa;
		this.numImpUnit = numImpUnit;
		this.intNumSerie = intNumSerie;
		this.numCntIngreso = numCntIngreso;
		this.numCntSalida = numCntSalida;
		this.numCntStock = numCntStock;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodPartida = chrCodPartida;
		this.chrCodCuenta = chrCodCuenta;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TDetalleIngresoses = TDetalleIngresoses;
		this.TDetalleBoletos = TDetalleBoletos;
	}

	@Id
	@SequenceGenerator(name = "seq_tari_boleto", sequenceName = "mig.t_tari_boleto_srl_id_boleto_seq")
	@GeneratedValue(generator = "seq_tari_boleto")
	@Column(name = "srl_id_boleto", unique = true, nullable = false)
	public int getSrlIdBoleto() {
		return this.srlIdBoleto;
	}

	public void setSrlIdBoleto(int srlIdBoleto) {
		this.srlIdBoleto = srlIdBoleto;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idunidad")
	public Unidadoperativa getUnidadoperativa() {
		return this.unidadoperativa;
	}

	public void setUnidadoperativa(Unidadoperativa unidadoperativa) {
		this.unidadoperativa = unidadoperativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_adm")
	public TbtRegistroNac getTbtRegistroNac() {
		return this.tbtRegistroNac;
	}

	public void setTbtRegistroNac(TbtRegistroNac tbtRegistroNac) {
		this.tbtRegistroNac = tbtRegistroNac;
	}	

	@Column(name = "chr_nom_boleto", length = 50)
	public String getChrNomBoleto() {
		return this.chrNomBoleto;
	}

	public void setChrNomBoleto(String chrNomBoleto) {
		this.chrNomBoleto = chrNomBoleto;
	}

	@Column(name = "chr_cod_boleto", length = 3)
	public String getChrCodBoleto() {
		return this.chrCodBoleto;
	}

	public void setChrCodBoleto(String chrCodBoleto) {
		this.chrCodBoleto = chrCodBoleto;
	}

	@Column(name = "int_idf_tarifa")
	public Integer getIntIdfTarifa() {
		return this.intIdfTarifa;
	}

	public void setIntIdfTarifa(Integer intIdfTarifa) {
		this.intIdfTarifa = intIdfTarifa;
	}

	@Column(name = "num_imp_unit", precision = 10)
	public BigDecimal getNumImpUnit() {
		return this.numImpUnit;
	}

	public void setNumImpUnit(BigDecimal numImpUnit) {
		this.numImpUnit = numImpUnit;
	}

	@Column(name = "int_num_serie")
	public String getIntNumSerie() {
		return this.intNumSerie;
	}

	public void setIntNumSerie(String intNumSerie) {
		this.intNumSerie = intNumSerie;
	}

	@Column(name = "num_cnt_ingreso")
	public Integer getNumCntIngreso() {
		return this.numCntIngreso;
	}

	public void setNumCntIngreso(Integer numCntIngreso) {
		this.numCntIngreso = numCntIngreso;
	}

	@Column(name = "num_cnt_salida")
	public Integer getNumCntSalida() {
		return this.numCntSalida;
	}

	public void setNumCntSalida(Integer numCntSalida) {
		this.numCntSalida = numCntSalida;
	}

	@Column(name = "num_cnt_stock")
	public Integer getNumCntStock() {
		return this.numCntStock;
	}

	public void setNumCntStock(Integer numCntStock) {
		this.numCntStock = numCntStock;
	}
	
	@Column(name = "num_inicio")
	public Integer getNumInicio() {
		return this.numInicio;
	}

	public void setNumInicio(Integer numInicio) {
		this.numInicio = numInicio;
	}

	@Column(name = "num_final")
	public Integer getNumFinal() {
		return this.numFinal;
	}

	public void setNumFinal(Integer numFinal) {
		this.numFinal = numFinal;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_partida", length = 15)
	public String getChrCodPartida() {
		return this.chrCodPartida;
	}

	public void setChrCodPartida(String chrCodPartida) {
		this.chrCodPartida = chrCodPartida;
	}

	@Column(name = "chr_cod_cuenta", length = 15)
	public String getChrCodCuenta() {
		return this.chrCodCuenta;
	}

	public void setChrCodCuenta(String chrCodCuenta) {
		this.chrCodCuenta = chrCodCuenta;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTariBoleto")
	public Set<TDetalleIngresos> getTDetalleIngresoses() {
		return this.TDetalleIngresoses;
	}

	public void setTDetalleIngresoses(Set<TDetalleIngresos> TDetalleIngresoses) {
		this.TDetalleIngresoses = TDetalleIngresoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTariBoleto")
	public Set<TDetalleBoleto> getTDetalleBoletos() {
		return this.TDetalleBoletos;
	}

	public void setTDetalleBoletos(Set<TDetalleBoleto> TDetalleBoletos) {
		this.TDetalleBoletos = TDetalleBoletos;
	}
	/**
	 * @return the chrNomCuenta
	 */
	@Column(name = "chr_nom_cuenta", length = 150)
	public String getChrNomCuenta() {
		return chrNomCuenta;
	}

	/**
	 * @param chrNomCuenta the chrNomCuenta to set
	 */
	public void setChrNomCuenta(String chrNomCuenta) {
		this.chrNomCuenta = chrNomCuenta;
	}

}
