package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTipoProveedor generated by hbm2java
 */
@Entity
@Table(name = "t_tipo_proveedor", schema = "mig")
public class TTipoProveedor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdProveedor;
	private TDocumentoIdentidad TDocumentoIdentidad;
	private Long numRuc;
	private String chrTipProveedor;
	private String chrTipEstado;
	private String chrRazSocial;
	private String chrNumDocumento;
	private String chrNombres;
	private String chrApePaterno;
	private String chrApeMaterno;
	private String chrDireccion;
	private String chrTelefono;
	private String chrMail;
	private String chrGiro;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TComprasIngresos> TComprasIngresoses = new HashSet<TComprasIngresos>(0);
	private Set<TContratos> TContratoses = new HashSet<TContratos>(0);
	private Set<TCartaFianza> TCartaFianzas = new HashSet<TCartaFianza>(0);

	public TTipoProveedor() {
	}

	public TTipoProveedor(int srlIdProveedor) {
		this.srlIdProveedor = srlIdProveedor;
	}

	public TTipoProveedor(int srlIdProveedor, TDocumentoIdentidad TDocumentoIdentidad, Long numRuc,
			String chrTipProveedor, String chrTipEstado, String chrRazSocial, String chrNumDocumento,
			String chrNombres, String chrApePaterno, String chrApeMaterno, String chrDireccion, String chrTelefono,
			String chrMail, String chrGiro, String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion,
			String chrCodUsuaModifica, Date dteFecModifica, Set<TComprasIngresos> TComprasIngresoses,
			Set<TContratos> TContratoses, Set<TCartaFianza> TCartaFianzas) {
		this.srlIdProveedor = srlIdProveedor;
		this.TDocumentoIdentidad = TDocumentoIdentidad;
		this.numRuc = numRuc;
		this.chrTipProveedor = chrTipProveedor;
		this.chrTipEstado = chrTipEstado;
		this.chrRazSocial = chrRazSocial;
		this.chrNumDocumento = chrNumDocumento;
		this.chrNombres = chrNombres;
		this.chrApePaterno = chrApePaterno;
		this.chrApeMaterno = chrApeMaterno;
		this.chrDireccion = chrDireccion;
		this.chrTelefono = chrTelefono;
		this.chrMail = chrMail;
		this.chrGiro = chrGiro;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TComprasIngresoses = TComprasIngresoses;
		this.TContratoses = TContratoses;
		this.TCartaFianzas = TCartaFianzas;
	}

	@Id
	@SequenceGenerator(name = "seq_tipo_proveedor", sequenceName = "mig.t_tipo_proveedor_srl_id_proveedor_seq")
	@GeneratedValue(generator = "seq_tipo_proveedor")
	@Column(name = "srl_id_proveedor", unique = true, nullable = false)
	public int getSrlIdProveedor() {
		return this.srlIdProveedor;
	}

	public void setSrlIdProveedor(int srlIdProveedor) {
		this.srlIdProveedor = srlIdProveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "srl_id_documento")
	public TDocumentoIdentidad getTDocumentoIdentidad() {
		return this.TDocumentoIdentidad;
	}

	public void setTDocumentoIdentidad(TDocumentoIdentidad TDocumentoIdentidad) {
		this.TDocumentoIdentidad = TDocumentoIdentidad;
	}

	@Column(name = "num_ruc", precision = 11, scale = 0)
	public Long getNumRuc() {
		return this.numRuc;
	}

	public void setNumRuc(Long numRuc) {
		this.numRuc = numRuc;
	}

	@Column(name = "chr_tip_proveedor", length = 1)
	public String getChrTipProveedor() {
		return this.chrTipProveedor;
	}

	public void setChrTipProveedor(String chrTipProveedor) {
		this.chrTipProveedor = chrTipProveedor;
	}

	@Column(name = "chr_tip_estado", length = 1)
	public String getChrTipEstado() {
		return this.chrTipEstado;
	}

	public void setChrTipEstado(String chrTipEstado) {
		this.chrTipEstado = chrTipEstado;
	}

	@Column(name = "chr_raz_social", length = 100)
	public String getChrRazSocial() {
		return this.chrRazSocial;
	}

	public void setChrRazSocial(String chrRazSocial) {
		this.chrRazSocial = chrRazSocial;
	}

	@Column(name = "chr_num_documento", length = 14)
	public String getChrNumDocumento() {
		return this.chrNumDocumento;
	}

	public void setChrNumDocumento(String chrNumDocumento) {
		this.chrNumDocumento = chrNumDocumento;
	}

	@Column(name = "chr_nombres", length = 30)
	public String getChrNombres() {
		return this.chrNombres;
	}

	public void setChrNombres(String chrNombres) {
		this.chrNombres = chrNombres;
	}

	@Column(name = "chr_ape_paterno", length = 30)
	public String getChrApePaterno() {
		return this.chrApePaterno;
	}

	public void setChrApePaterno(String chrApePaterno) {
		this.chrApePaterno = chrApePaterno;
	}

	@Column(name = "chr_ape_materno", length = 30)
	public String getChrApeMaterno() {
		return this.chrApeMaterno;
	}

	public void setChrApeMaterno(String chrApeMaterno) {
		this.chrApeMaterno = chrApeMaterno;
	}

	@Column(name = "chr_direccion", length = 100)
	public String getChrDireccion() {
		return this.chrDireccion;
	}

	public void setChrDireccion(String chrDireccion) {
		this.chrDireccion = chrDireccion;
	}

	@Column(name = "chr_telefono", length = 11)
	public String getChrTelefono() {
		return this.chrTelefono;
	}

	public void setChrTelefono(String chrTelefono) {
		this.chrTelefono = chrTelefono;
	}

	@Column(name = "chr_mail", length = 30)
	public String getChrMail() {
		return this.chrMail;
	}

	public void setChrMail(String chrMail) {
		this.chrMail = chrMail;
	}

	@Column(name = "chr_giro", length = 50)
	public String getChrGiro() {
		return this.chrGiro;
	}

	public void setChrGiro(String chrGiro) {
		this.chrGiro = chrGiro;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTipoProveedor")
	public Set<TComprasIngresos> getTComprasIngresoses() {
		return this.TComprasIngresoses;
	}

	public void setTComprasIngresoses(Set<TComprasIngresos> TComprasIngresoses) {
		this.TComprasIngresoses = TComprasIngresoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTipoProveedor")
	public Set<TContratos> getTContratoses() {
		return this.TContratoses;
	}

	public void setTContratoses(Set<TContratos> TContratoses) {
		this.TContratoses = TContratoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTipoProveedor")
	public Set<TCartaFianza> getTCartaFianzas() {
		return this.TCartaFianzas;
	}

	public void setTCartaFianzas(Set<TCartaFianza> TCartaFianzas) {
		this.TCartaFianzas = TCartaFianzas;
	}

}
