package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTipoMoneda generated by hbm2java
 */
@Entity
@Table(name = "t_tipo_moneda", schema = "mig")
public class TTipoMoneda implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdMoneda;
	private String chrCodMoneda;
	private String chrNomMoneda;
	private String chrSiglas;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TTransferencia> TTransferencias = new HashSet<TTransferencia>(0);
	private Set<TComprasIngresos> TComprasIngresoses = new HashSet<TComprasIngresos>(0);

	public TTipoMoneda() {
	}

	public TTipoMoneda(int srlIdMoneda) {
		this.srlIdMoneda = srlIdMoneda;
	}

	public TTipoMoneda(int srlIdMoneda, String chrCodMoneda, String chrNomMoneda, String chrSiglas,
			String chrFlgActivo, String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica,
			Date dteFecModifica, Set<TTransferencia> TTransferencias, Set<TComprasIngresos> TComprasIngresoses) {
		this.srlIdMoneda = srlIdMoneda;
		this.chrCodMoneda = chrCodMoneda;
		this.chrNomMoneda = chrNomMoneda;
		this.chrSiglas = chrSiglas;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TTransferencias = TTransferencias;
		this.TComprasIngresoses = TComprasIngresoses;
	}

	@Id
	@SequenceGenerator(name = "seq_tipo_moneda", sequenceName = "mig.t_tipo_moneda_srl_id_moneda_seq")
	@GeneratedValue(generator = "seq_tipo_moneda")
	@Column(name = "srl_id_moneda", unique = true, nullable = false)
	public int getSrlIdMoneda() {
		return this.srlIdMoneda;
	}

	public void setSrlIdMoneda(int srlIdMoneda) {
		this.srlIdMoneda = srlIdMoneda;
	}

	@Column(name = "chr_cod_moneda", length = 1)
	public String getChrCodMoneda() {
		return this.chrCodMoneda;
	}

	public void setChrCodMoneda(String chrCodMoneda) {
		this.chrCodMoneda = chrCodMoneda;
	}

	@Column(name = "chr_nom_moneda", length = 50)
	public String getChrNomMoneda() {
		return this.chrNomMoneda;
	}

	public void setChrNomMoneda(String chrNomMoneda) {
		this.chrNomMoneda = chrNomMoneda;
	}

	@Column(name = "chr_siglas", length = 3)
	public String getChrSiglas() {
		return this.chrSiglas;
	}

	public void setChrSiglas(String chrSiglas) {
		this.chrSiglas = chrSiglas;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTipoMoneda")
	public Set<TTransferencia> getTTransferencias() {
		return this.TTransferencias;
	}

	public void setTTransferencias(Set<TTransferencia> TTransferencias) {
		this.TTransferencias = TTransferencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTipoMoneda")
	public Set<TComprasIngresos> getTComprasIngresoses() {
		return this.TComprasIngresoses;
	}

	public void setTComprasIngresoses(Set<TComprasIngresos> TComprasIngresoses) {
		this.TComprasIngresoses = TComprasIngresoses;
	}

}
