package pe.com.mig.model.entity;
// Generated 22/06/2016 01:16:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TUnidadMedida generated by hbm2java
 */
@Entity
@Table(name = "t_unidad_medida", schema = "mig", uniqueConstraints = @UniqueConstraint(columnNames = "chr_cod_unidad"))
public class TUnidadMedida implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdUnidad;
	private String chrCodUnidad;
	private String chrNomUnidad;
	private String chrFlgActiva;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TProducto> TProductos = new HashSet<TProducto>(0);

	public TUnidadMedida() {
	}

	public TUnidadMedida(int srlIdUnidad) {
		this.srlIdUnidad = srlIdUnidad;
	}

	public TUnidadMedida(int srlIdUnidad, String chrCodUnidad, String chrNomUnidad, String chrFlgActiva,
			String chrCodUsuaCreacion, Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TProducto> TProductos) {
		this.srlIdUnidad = srlIdUnidad;
		this.chrCodUnidad = chrCodUnidad;
		this.chrNomUnidad = chrNomUnidad;
		this.chrFlgActiva = chrFlgActiva;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TProductos = TProductos;
	}

	@Id
	@SequenceGenerator(name = "seq_unidad_medida", sequenceName = "mig.t_unidad_medida_srl_id_unidad_seq")
	@GeneratedValue(generator = "seq_unidad_medida")
	@Column(name = "srl_id_unidad", unique = true, nullable = false)
	public int getSrlIdUnidad() {
		return this.srlIdUnidad;
	}

	public void setSrlIdUnidad(int srlIdUnidad) {
		this.srlIdUnidad = srlIdUnidad;
	}

	@Column(name = "chr_cod_unidad", unique = true, length = 2)
	public String getChrCodUnidad() {
		return this.chrCodUnidad;
	}

	public void setChrCodUnidad(String chrCodUnidad) {
		this.chrCodUnidad = chrCodUnidad;
	}

	@Column(name = "chr_nom_unidad", length = 50)
	public String getChrNomUnidad() {
		return this.chrNomUnidad;
	}

	public void setChrNomUnidad(String chrNomUnidad) {
		this.chrNomUnidad = chrNomUnidad;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActiva() {
		return this.chrFlgActiva;
	}

	public void setChrFlgActiva(String chrFlgActiva) {
		this.chrFlgActiva = chrFlgActiva;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUnidadMedida")
	public Set<TProducto> getTProductos() {
		return this.TProductos;
	}

	public void setTProductos(Set<TProducto> TProductos) {
		this.TProductos = TProductos;
	}

}
