package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TVia generated by hbm2java
 */
@Entity
@Table(name = "t_via", schema = "mig")
public class TVia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdVia;
	private String chrCodVia;
	private String chrNomVia;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TPersonalCuarta> TPersonalCuartas = new HashSet<TPersonalCuarta>(0);

	public TVia() {
	}

	public TVia(int srlIdVia) {
		this.srlIdVia = srlIdVia;
	}

	public TVia(int srlIdVia, String chrCodVia, String chrNomVia, String chrFlgActivo, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TPersonalCuarta> TPersonalCuartas) {
		this.srlIdVia = srlIdVia;
		this.chrCodVia = chrCodVia;
		this.chrNomVia = chrNomVia;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TPersonalCuartas = TPersonalCuartas;
	}

	@Id
	@SequenceGenerator(name = "seq_via", sequenceName = "mig.t_via_srl_id_via_seq")
	@GeneratedValue(generator = "seq_via")
	@Column(name = "srl_id_via", unique = true, nullable = false)
	public int getSrlIdVia() {
		return this.srlIdVia;
	}

	public void setSrlIdVia(int srlIdVia) {
		this.srlIdVia = srlIdVia;
	}

	@Column(name = "chr_cod_via", length = 2)
	public String getChrCodVia() {
		return this.chrCodVia;
	}

	public void setChrCodVia(String chrCodVia) {
		this.chrCodVia = chrCodVia;
	}

	@Column(name = "chr_nom_via", length = 20)
	public String getChrNomVia() {
		return this.chrNomVia;
	}

	public void setChrNomVia(String chrNomVia) {
		this.chrNomVia = chrNomVia;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TVia")
	public Set<TPersonalCuarta> getTPersonalCuartas() {
		return this.TPersonalCuartas;
	}

	public void setTPersonalCuartas(Set<TPersonalCuarta> TPersonalCuartas) {
		this.TPersonalCuartas = TPersonalCuartas;
	}

}
