package pe.com.mig.model.entity;
// Generated 10/07/2016 06:15:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TZona generated by hbm2java
 */
@Entity
@Table(name = "t_zona", schema = "mig")
public class TZona implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int srlIdZona;
	private String chrCodZona;
	private String chrNomZona;
	private String chrFlgActivo;
	private String chrCodUsuaCreacion;
	private Date dteFecCreacion;
	private String chrCodUsuaModifica;
	private Date dteFecModifica;
	private Set<TPersonalCuarta> TPersonalCuartas = new HashSet<TPersonalCuarta>(0);

	public TZona() {
	}

	public TZona(int srlIdZona) {
		this.srlIdZona = srlIdZona;
	}

	public TZona(int srlIdZona, String chrCodZona, String chrNomZona, String chrFlgActivo, String chrCodUsuaCreacion,
			Date dteFecCreacion, String chrCodUsuaModifica, Date dteFecModifica,
			Set<TPersonalCuarta> TPersonalCuartas) {
		this.srlIdZona = srlIdZona;
		this.chrCodZona = chrCodZona;
		this.chrNomZona = chrNomZona;
		this.chrFlgActivo = chrFlgActivo;
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
		this.dteFecCreacion = dteFecCreacion;
		this.chrCodUsuaModifica = chrCodUsuaModifica;
		this.dteFecModifica = dteFecModifica;
		this.TPersonalCuartas = TPersonalCuartas;
	}

	@Id
	@SequenceGenerator(name = "seq_zona", sequenceName = "mig.t_zona_srl_id_zona_seq")
	@GeneratedValue(generator = "seq_zona")
	@Column(name = "srl_id_zona", unique = true, nullable = false)
	public int getSrlIdZona() {
		return this.srlIdZona;
	}

	public void setSrlIdZona(int srlIdZona) {
		this.srlIdZona = srlIdZona;
	}

	@Column(name = "chr_cod_zona", length = 2)
	public String getChrCodZona() {
		return this.chrCodZona;
	}

	public void setChrCodZona(String chrCodZona) {
		this.chrCodZona = chrCodZona;
	}

	@Column(name = "chr_nom_zona", length = 40)
	public String getChrNomZona() {
		return this.chrNomZona;
	}

	public void setChrNomZona(String chrNomZona) {
		this.chrNomZona = chrNomZona;
	}

	@Column(name = "chr_flg_activo", length = 1)
	public String getChrFlgActivo() {
		return this.chrFlgActivo;
	}

	public void setChrFlgActivo(String chrFlgActivo) {
		this.chrFlgActivo = chrFlgActivo;
	}

	@Column(name = "chr_cod_usua_creacion", length = 20)
	public String getChrCodUsuaCreacion() {
		return this.chrCodUsuaCreacion;
	}

	public void setChrCodUsuaCreacion(String chrCodUsuaCreacion) {
		this.chrCodUsuaCreacion = chrCodUsuaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_creacion", length = 13)
	public Date getDteFecCreacion() {
		return this.dteFecCreacion;
	}

	public void setDteFecCreacion(Date dteFecCreacion) {
		this.dteFecCreacion = dteFecCreacion;
	}

	@Column(name = "chr_cod_usua_modifica", length = 20)
	public String getChrCodUsuaModifica() {
		return this.chrCodUsuaModifica;
	}

	public void setChrCodUsuaModifica(String chrCodUsuaModifica) {
		this.chrCodUsuaModifica = chrCodUsuaModifica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dte_fec_modifica", length = 13)
	public Date getDteFecModifica() {
		return this.dteFecModifica;
	}

	public void setDteFecModifica(Date dteFecModifica) {
		this.dteFecModifica = dteFecModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TZona")
	public Set<TPersonalCuarta> getTPersonalCuartas() {
		return this.TPersonalCuartas;
	}

	public void setTPersonalCuartas(Set<TPersonalCuarta> TPersonalCuartas) {
		this.TPersonalCuartas = TPersonalCuartas;
	}

}
