package pe.com.mig.model.entity.sde;
// Generated 22/06/2016 09:23:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbtRegistroNac generated by hbm2java
 */

@Entity
@Table(name = "tbt_registro_nac", schema = "sde")
public class TbtRegistroNac implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int objectid;
	private Integer idRanac;
	private String nombre;
	private String codanp;

	public TbtRegistroNac() {
	}

	public TbtRegistroNac(int idRanac) {
		this.idRanac = idRanac;
	}

	@Column(name = "objectid", unique = true, nullable = false)
	public int getObjectid() {
		return this.objectid;
	}

	public void setObjectid(int objectid) {
		this.objectid = objectid;
	}

	@Id
	@Column(name = "id_ranac")
	public Integer getIdRanac() {
		return this.idRanac;
	}

	public void setIdRanac(Integer idRanac) {
		this.idRanac = idRanac;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codanp", length = 10)
	public String getCodanp() {
		return this.codanp;
	}
	
	public void setCodanp(String codanp) {
		this.codanp = codanp;
	}
	
}
